// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hestonEuro_simulation (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        this_data_timeT_val1,
        this_data_freeRate_val2,
        this_data_initPrice_val3,
        this_data_strikePrice_val4,
        this_vol_expect_val5,
        this_vol_kappa_val6,
        p_read,
        this_vol_initValue_val7,
        this_vol_correlation_val8,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] this_data_timeT_val1;
input  [31:0] this_data_freeRate_val2;
input  [31:0] this_data_initPrice_val3;
input  [31:0] this_data_strikePrice_val4;
input  [31:0] this_vol_expect_val5;
input  [31:0] this_vol_kappa_val6;
input  [31:0] p_read;
input  [31:0] this_vol_initValue_val7;
input  [31:0] this_vol_correlation_val8;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ap_return_0;
reg[31:0] ap_return_1;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [9:0] shl_ln_fu_405_p3;
reg   [9:0] shl_ln_reg_742;
wire    ap_CS_fsm_state2;
wire  signed [31:0] xor_ln72_fu_451_p2;
reg  signed [31:0] xor_ln72_reg_747;
wire  signed [31:0] xor_ln72_1_fu_499_p2;
reg  signed [31:0] xor_ln72_1_reg_752;
wire  signed [31:0] xor_ln72_2_fu_547_p2;
reg  signed [31:0] xor_ln72_2_reg_757;
wire  signed [31:0] xor_ln72_3_fu_595_p2;
reg  signed [31:0] xor_ln72_3_reg_762;
reg   [8:0] mt_rng_mt_e_address0;
reg    mt_rng_mt_e_ce0;
reg    mt_rng_mt_e_we0;
reg   [31:0] mt_rng_mt_e_d0;
wire   [31:0] mt_rng_mt_e_q0;
reg    mt_rng_mt_e_ce1;
wire   [31:0] mt_rng_mt_e_q1;
reg   [8:0] mt_rng_mt_e_1_address0;
reg    mt_rng_mt_e_1_ce0;
reg    mt_rng_mt_e_1_we0;
reg   [31:0] mt_rng_mt_e_1_d0;
wire   [31:0] mt_rng_mt_e_1_q0;
reg    mt_rng_mt_e_1_ce1;
wire   [31:0] mt_rng_mt_e_1_q1;
reg   [8:0] mt_rng_mt_e_2_address0;
reg    mt_rng_mt_e_2_ce0;
reg    mt_rng_mt_e_2_we0;
reg   [31:0] mt_rng_mt_e_2_d0;
wire   [31:0] mt_rng_mt_e_2_q0;
reg    mt_rng_mt_e_2_ce1;
wire   [31:0] mt_rng_mt_e_2_q1;
reg   [8:0] mt_rng_mt_e_3_address0;
reg    mt_rng_mt_e_3_ce0;
reg    mt_rng_mt_e_3_we0;
reg   [31:0] mt_rng_mt_e_3_d0;
wire   [31:0] mt_rng_mt_e_3_q0;
reg    mt_rng_mt_e_3_ce1;
wire   [31:0] mt_rng_mt_e_3_q1;
reg   [8:0] mt_rng_mt_o_address0;
reg    mt_rng_mt_o_ce0;
reg    mt_rng_mt_o_we0;
reg   [31:0] mt_rng_mt_o_d0;
wire   [31:0] mt_rng_mt_o_q0;
reg    mt_rng_mt_o_ce1;
wire   [31:0] mt_rng_mt_o_q1;
reg   [8:0] mt_rng_mt_o_1_address0;
reg    mt_rng_mt_o_1_ce0;
reg    mt_rng_mt_o_1_we0;
reg   [31:0] mt_rng_mt_o_1_d0;
wire   [31:0] mt_rng_mt_o_1_q0;
reg    mt_rng_mt_o_1_ce1;
wire   [31:0] mt_rng_mt_o_1_q1;
reg   [8:0] mt_rng_mt_o_2_address0;
reg    mt_rng_mt_o_2_ce0;
reg    mt_rng_mt_o_2_we0;
reg   [31:0] mt_rng_mt_o_2_d0;
wire   [31:0] mt_rng_mt_o_2_q0;
reg    mt_rng_mt_o_2_ce1;
wire   [31:0] mt_rng_mt_o_2_q1;
reg   [8:0] mt_rng_mt_o_3_address0;
reg    mt_rng_mt_o_3_ce0;
reg    mt_rng_mt_o_3_we0;
reg   [31:0] mt_rng_mt_o_3_d0;
wire   [31:0] mt_rng_mt_o_3_q0;
reg    mt_rng_mt_o_3_ce1;
wire   [31:0] mt_rng_mt_o_3_q1;
wire    grp_sampleSIM_fu_274_ap_start;
wire    grp_sampleSIM_fu_274_ap_done;
wire    grp_sampleSIM_fu_274_ap_idle;
wire    grp_sampleSIM_fu_274_ap_ready;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_e_0_address0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_e_0_we0;
wire   [31:0] grp_sampleSIM_fu_274_mt_rng_mt_e_0_d0;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_e_0_address1;
wire    grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce1;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_e_1_address0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_e_1_we0;
wire   [31:0] grp_sampleSIM_fu_274_mt_rng_mt_e_1_d0;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_e_1_address1;
wire    grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce1;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_e_2_address0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_e_2_we0;
wire   [31:0] grp_sampleSIM_fu_274_mt_rng_mt_e_2_d0;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_e_2_address1;
wire    grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce1;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_e_3_address0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_e_3_we0;
wire   [31:0] grp_sampleSIM_fu_274_mt_rng_mt_e_3_d0;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_e_3_address1;
wire    grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce1;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_o_0_address0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_o_0_we0;
wire   [31:0] grp_sampleSIM_fu_274_mt_rng_mt_o_0_d0;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_o_0_address1;
wire    grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce1;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_o_1_address0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_o_1_we0;
wire   [31:0] grp_sampleSIM_fu_274_mt_rng_mt_o_1_d0;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_o_1_address1;
wire    grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce1;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_o_2_address0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_o_2_we0;
wire   [31:0] grp_sampleSIM_fu_274_mt_rng_mt_o_2_d0;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_o_2_address1;
wire    grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce1;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_o_3_address0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce0;
wire    grp_sampleSIM_fu_274_mt_rng_mt_o_3_we0;
wire   [31:0] grp_sampleSIM_fu_274_mt_rng_mt_o_3_d0;
wire   [8:0] grp_sampleSIM_fu_274_mt_rng_mt_o_3_address1;
wire    grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce1;
wire   [31:0] grp_sampleSIM_fu_274_ap_return_0;
wire   [31:0] grp_sampleSIM_fu_274_ap_return_1;
reg    grp_sampleSIM_fu_274_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln64_fu_379_p1;
wire   [0:0] icmp_ln64_fu_351_p2;
reg   [31:0] add484_i_fu_72;
wire   [31:0] add_ln72_1_fu_615_p2;
wire    ap_CS_fsm_state3;
reg   [31:0] add48_15_i_fu_76;
wire   [31:0] add_ln72_2_fu_621_p2;
reg   [31:0] add48_26_i_fu_80;
wire   [31:0] add_ln72_3_fu_627_p2;
reg   [31:0] add48_37_i_fu_84;
wire   [31:0] add_ln72_4_fu_633_p2;
reg   [8:0] i_fu_88;
wire   [8:0] add_ln64_fu_357_p2;
wire   [31:0] add_ln70_fu_430_p2;
wire   [31:0] add_ln70_1_fu_478_p2;
wire   [31:0] add_ln70_2_fu_526_p2;
wire   [31:0] add_ln70_3_fu_574_p2;
reg  signed [31:0] grp_fu_303_p0;
wire  signed [31:0] xor_ln70_fu_423_p2;
reg  signed [31:0] grp_fu_308_p0;
wire  signed [31:0] xor_ln70_1_fu_471_p2;
reg  signed [31:0] grp_fu_313_p0;
wire  signed [31:0] xor_ln70_2_fu_519_p2;
reg  signed [31:0] grp_fu_318_p0;
wire  signed [31:0] xor_ln70_3_fu_567_p2;
wire   [1:0] lshr_ln_fu_391_p4;
wire   [9:0] or_ln70_fu_413_p2;
wire   [31:0] zext_ln70_1_fu_401_p1;
wire   [31:0] grp_fu_303_p2;
wire   [31:0] zext_ln70_fu_419_p1;
wire   [1:0] lshr_ln1_fu_437_p4;
wire   [31:0] zext_ln72_1_fu_447_p1;
wire   [1:0] lshr_ln70_1_fu_457_p4;
wire   [31:0] zext_ln70_2_fu_467_p1;
wire   [31:0] grp_fu_308_p2;
wire   [1:0] lshr_ln72_1_fu_485_p4;
wire   [31:0] zext_ln72_2_fu_495_p1;
wire   [1:0] lshr_ln70_2_fu_505_p4;
wire   [31:0] zext_ln70_3_fu_515_p1;
wire   [31:0] grp_fu_313_p2;
wire   [1:0] lshr_ln72_2_fu_533_p4;
wire   [31:0] zext_ln72_3_fu_543_p1;
wire   [1:0] lshr_ln70_3_fu_553_p4;
wire   [31:0] zext_ln70_4_fu_563_p1;
wire   [31:0] grp_fu_318_p2;
wire   [1:0] lshr_ln72_3_fu_581_p4;
wire   [31:0] zext_ln72_4_fu_591_p1;
wire   [9:0] add_ln72_fu_606_p2;
wire   [31:0] zext_ln72_fu_611_p1;
reg   [31:0] ap_return_0_preg;
reg   [31:0] ap_return_1_preg;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 shl_ln_reg_742 = 10'd0;
#0 xor_ln72_reg_747 = 32'd0;
#0 xor_ln72_1_reg_752 = 32'd0;
#0 xor_ln72_2_reg_757 = 32'd0;
#0 xor_ln72_3_reg_762 = 32'd0;
#0 grp_sampleSIM_fu_274_ap_start_reg = 1'b0;
#0 add484_i_fu_72 = 32'd0;
#0 add48_15_i_fu_76 = 32'd0;
#0 add48_26_i_fu_80 = 32'd0;
#0 add48_37_i_fu_84 = 32'd0;
#0 i_fu_88 = 9'd0;
#0 ap_return_0_preg = 32'd0;
#0 ap_return_1_preg = 32'd0;
end

hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 312 ),
    .AddressWidth( 9 ))
mt_rng_mt_e_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mt_rng_mt_e_address0),
    .ce0(mt_rng_mt_e_ce0),
    .we0(mt_rng_mt_e_we0),
    .d0(mt_rng_mt_e_d0),
    .q0(mt_rng_mt_e_q0),
    .address1(grp_sampleSIM_fu_274_mt_rng_mt_e_0_address1),
    .ce1(mt_rng_mt_e_ce1),
    .q1(mt_rng_mt_e_q1)
);

hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 312 ),
    .AddressWidth( 9 ))
mt_rng_mt_e_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mt_rng_mt_e_1_address0),
    .ce0(mt_rng_mt_e_1_ce0),
    .we0(mt_rng_mt_e_1_we0),
    .d0(mt_rng_mt_e_1_d0),
    .q0(mt_rng_mt_e_1_q0),
    .address1(grp_sampleSIM_fu_274_mt_rng_mt_e_1_address1),
    .ce1(mt_rng_mt_e_1_ce1),
    .q1(mt_rng_mt_e_1_q1)
);

hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 312 ),
    .AddressWidth( 9 ))
mt_rng_mt_e_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mt_rng_mt_e_2_address0),
    .ce0(mt_rng_mt_e_2_ce0),
    .we0(mt_rng_mt_e_2_we0),
    .d0(mt_rng_mt_e_2_d0),
    .q0(mt_rng_mt_e_2_q0),
    .address1(grp_sampleSIM_fu_274_mt_rng_mt_e_2_address1),
    .ce1(mt_rng_mt_e_2_ce1),
    .q1(mt_rng_mt_e_2_q1)
);

hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 312 ),
    .AddressWidth( 9 ))
mt_rng_mt_e_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mt_rng_mt_e_3_address0),
    .ce0(mt_rng_mt_e_3_ce0),
    .we0(mt_rng_mt_e_3_we0),
    .d0(mt_rng_mt_e_3_d0),
    .q0(mt_rng_mt_e_3_q0),
    .address1(grp_sampleSIM_fu_274_mt_rng_mt_e_3_address1),
    .ce1(mt_rng_mt_e_3_ce1),
    .q1(mt_rng_mt_e_3_q1)
);

hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 312 ),
    .AddressWidth( 9 ))
mt_rng_mt_o_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mt_rng_mt_o_address0),
    .ce0(mt_rng_mt_o_ce0),
    .we0(mt_rng_mt_o_we0),
    .d0(mt_rng_mt_o_d0),
    .q0(mt_rng_mt_o_q0),
    .address1(grp_sampleSIM_fu_274_mt_rng_mt_o_0_address1),
    .ce1(mt_rng_mt_o_ce1),
    .q1(mt_rng_mt_o_q1)
);

hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 312 ),
    .AddressWidth( 9 ))
mt_rng_mt_o_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mt_rng_mt_o_1_address0),
    .ce0(mt_rng_mt_o_1_ce0),
    .we0(mt_rng_mt_o_1_we0),
    .d0(mt_rng_mt_o_1_d0),
    .q0(mt_rng_mt_o_1_q0),
    .address1(grp_sampleSIM_fu_274_mt_rng_mt_o_1_address1),
    .ce1(mt_rng_mt_o_1_ce1),
    .q1(mt_rng_mt_o_1_q1)
);

hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 312 ),
    .AddressWidth( 9 ))
mt_rng_mt_o_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mt_rng_mt_o_2_address0),
    .ce0(mt_rng_mt_o_2_ce0),
    .we0(mt_rng_mt_o_2_we0),
    .d0(mt_rng_mt_o_2_d0),
    .q0(mt_rng_mt_o_2_q0),
    .address1(grp_sampleSIM_fu_274_mt_rng_mt_o_2_address1),
    .ce1(mt_rng_mt_o_2_ce1),
    .q1(mt_rng_mt_o_2_q1)
);

hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 312 ),
    .AddressWidth( 9 ))
mt_rng_mt_o_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mt_rng_mt_o_3_address0),
    .ce0(mt_rng_mt_o_3_ce0),
    .we0(mt_rng_mt_o_3_we0),
    .d0(mt_rng_mt_o_3_d0),
    .q0(mt_rng_mt_o_3_q0),
    .address1(grp_sampleSIM_fu_274_mt_rng_mt_o_3_address1),
    .ce1(mt_rng_mt_o_3_ce1),
    .q1(mt_rng_mt_o_3_q1)
);

hestonEuro_sampleSIM grp_sampleSIM_fu_274(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sampleSIM_fu_274_ap_start),
    .ap_done(grp_sampleSIM_fu_274_ap_done),
    .ap_idle(grp_sampleSIM_fu_274_ap_idle),
    .ap_ready(grp_sampleSIM_fu_274_ap_ready),
    .this_data_timeT_val(this_data_timeT_val1),
    .this_data_freeRate_val(this_data_freeRate_val2),
    .this_data_initPrice_val(this_data_initPrice_val3),
    .this_data_strikePrice_val(this_data_strikePrice_val4),
    .this_vol_expect_val(this_vol_expect_val5),
    .this_vol_kappa_val(this_vol_kappa_val6),
    .p_read(p_read),
    .this_vol_initValue_val(this_vol_initValue_val7),
    .this_vol_correlation_val(this_vol_correlation_val8),
    .mt_rng_mt_e_0_address0(grp_sampleSIM_fu_274_mt_rng_mt_e_0_address0),
    .mt_rng_mt_e_0_ce0(grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce0),
    .mt_rng_mt_e_0_we0(grp_sampleSIM_fu_274_mt_rng_mt_e_0_we0),
    .mt_rng_mt_e_0_d0(grp_sampleSIM_fu_274_mt_rng_mt_e_0_d0),
    .mt_rng_mt_e_0_q0(mt_rng_mt_e_q0),
    .mt_rng_mt_e_0_address1(grp_sampleSIM_fu_274_mt_rng_mt_e_0_address1),
    .mt_rng_mt_e_0_ce1(grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce1),
    .mt_rng_mt_e_0_q1(mt_rng_mt_e_q1),
    .mt_rng_mt_e_1_address0(grp_sampleSIM_fu_274_mt_rng_mt_e_1_address0),
    .mt_rng_mt_e_1_ce0(grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce0),
    .mt_rng_mt_e_1_we0(grp_sampleSIM_fu_274_mt_rng_mt_e_1_we0),
    .mt_rng_mt_e_1_d0(grp_sampleSIM_fu_274_mt_rng_mt_e_1_d0),
    .mt_rng_mt_e_1_q0(mt_rng_mt_e_1_q0),
    .mt_rng_mt_e_1_address1(grp_sampleSIM_fu_274_mt_rng_mt_e_1_address1),
    .mt_rng_mt_e_1_ce1(grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce1),
    .mt_rng_mt_e_1_q1(mt_rng_mt_e_1_q1),
    .mt_rng_mt_e_2_address0(grp_sampleSIM_fu_274_mt_rng_mt_e_2_address0),
    .mt_rng_mt_e_2_ce0(grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce0),
    .mt_rng_mt_e_2_we0(grp_sampleSIM_fu_274_mt_rng_mt_e_2_we0),
    .mt_rng_mt_e_2_d0(grp_sampleSIM_fu_274_mt_rng_mt_e_2_d0),
    .mt_rng_mt_e_2_q0(mt_rng_mt_e_2_q0),
    .mt_rng_mt_e_2_address1(grp_sampleSIM_fu_274_mt_rng_mt_e_2_address1),
    .mt_rng_mt_e_2_ce1(grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce1),
    .mt_rng_mt_e_2_q1(mt_rng_mt_e_2_q1),
    .mt_rng_mt_e_3_address0(grp_sampleSIM_fu_274_mt_rng_mt_e_3_address0),
    .mt_rng_mt_e_3_ce0(grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce0),
    .mt_rng_mt_e_3_we0(grp_sampleSIM_fu_274_mt_rng_mt_e_3_we0),
    .mt_rng_mt_e_3_d0(grp_sampleSIM_fu_274_mt_rng_mt_e_3_d0),
    .mt_rng_mt_e_3_q0(mt_rng_mt_e_3_q0),
    .mt_rng_mt_e_3_address1(grp_sampleSIM_fu_274_mt_rng_mt_e_3_address1),
    .mt_rng_mt_e_3_ce1(grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce1),
    .mt_rng_mt_e_3_q1(mt_rng_mt_e_3_q1),
    .mt_rng_mt_o_0_address0(grp_sampleSIM_fu_274_mt_rng_mt_o_0_address0),
    .mt_rng_mt_o_0_ce0(grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce0),
    .mt_rng_mt_o_0_we0(grp_sampleSIM_fu_274_mt_rng_mt_o_0_we0),
    .mt_rng_mt_o_0_d0(grp_sampleSIM_fu_274_mt_rng_mt_o_0_d0),
    .mt_rng_mt_o_0_q0(mt_rng_mt_o_q0),
    .mt_rng_mt_o_0_address1(grp_sampleSIM_fu_274_mt_rng_mt_o_0_address1),
    .mt_rng_mt_o_0_ce1(grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce1),
    .mt_rng_mt_o_0_q1(mt_rng_mt_o_q1),
    .mt_rng_mt_o_1_address0(grp_sampleSIM_fu_274_mt_rng_mt_o_1_address0),
    .mt_rng_mt_o_1_ce0(grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce0),
    .mt_rng_mt_o_1_we0(grp_sampleSIM_fu_274_mt_rng_mt_o_1_we0),
    .mt_rng_mt_o_1_d0(grp_sampleSIM_fu_274_mt_rng_mt_o_1_d0),
    .mt_rng_mt_o_1_q0(mt_rng_mt_o_1_q0),
    .mt_rng_mt_o_1_address1(grp_sampleSIM_fu_274_mt_rng_mt_o_1_address1),
    .mt_rng_mt_o_1_ce1(grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce1),
    .mt_rng_mt_o_1_q1(mt_rng_mt_o_1_q1),
    .mt_rng_mt_o_2_address0(grp_sampleSIM_fu_274_mt_rng_mt_o_2_address0),
    .mt_rng_mt_o_2_ce0(grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce0),
    .mt_rng_mt_o_2_we0(grp_sampleSIM_fu_274_mt_rng_mt_o_2_we0),
    .mt_rng_mt_o_2_d0(grp_sampleSIM_fu_274_mt_rng_mt_o_2_d0),
    .mt_rng_mt_o_2_q0(mt_rng_mt_o_2_q0),
    .mt_rng_mt_o_2_address1(grp_sampleSIM_fu_274_mt_rng_mt_o_2_address1),
    .mt_rng_mt_o_2_ce1(grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce1),
    .mt_rng_mt_o_2_q1(mt_rng_mt_o_2_q1),
    .mt_rng_mt_o_3_address0(grp_sampleSIM_fu_274_mt_rng_mt_o_3_address0),
    .mt_rng_mt_o_3_ce0(grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce0),
    .mt_rng_mt_o_3_we0(grp_sampleSIM_fu_274_mt_rng_mt_o_3_we0),
    .mt_rng_mt_o_3_d0(grp_sampleSIM_fu_274_mt_rng_mt_o_3_d0),
    .mt_rng_mt_o_3_q0(mt_rng_mt_o_3_q0),
    .mt_rng_mt_o_3_address1(grp_sampleSIM_fu_274_mt_rng_mt_o_3_address1),
    .mt_rng_mt_o_3_ce1(grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce1),
    .mt_rng_mt_o_3_q1(mt_rng_mt_o_3_q1),
    .ap_return_0(grp_sampleSIM_fu_274_ap_return_0),
    .ap_return_1(grp_sampleSIM_fu_274_ap_return_1)
);

hestonEuro_mul_32s_32ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32ns_32_1_1_U261(
    .din0(grp_fu_303_p0),
    .din1(32'd1812433253),
    .dout(grp_fu_303_p2)
);

hestonEuro_mul_32s_32ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32ns_32_1_1_U262(
    .din0(grp_fu_308_p0),
    .din1(32'd1812433253),
    .dout(grp_fu_308_p2)
);

hestonEuro_mul_32s_32ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32ns_32_1_1_U263(
    .din0(grp_fu_313_p0),
    .din1(32'd1812433253),
    .dout(grp_fu_313_p2)
);

hestonEuro_mul_32s_32ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32ns_32_1_1_U264(
    .din0(grp_fu_318_p0),
    .din1(32'd1812433253),
    .dout(grp_fu_318_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        add484_i_fu_72 <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            add484_i_fu_72 <= 32'd0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            add484_i_fu_72 <= add_ln72_1_fu_615_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        add48_15_i_fu_76 <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            add48_15_i_fu_76 <= 32'd1;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            add48_15_i_fu_76 <= add_ln72_2_fu_621_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        add48_26_i_fu_80 <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            add48_26_i_fu_80 <= 32'd2;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            add48_26_i_fu_80 <= add_ln72_3_fu_627_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        add48_37_i_fu_84 <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            add48_37_i_fu_84 <= 32'd3;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            add48_37_i_fu_84 <= add_ln72_4_fu_633_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 32'd0;
    end else begin
        if (((grp_sampleSIM_fu_274_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_return_0_preg <= grp_sampleSIM_fu_274_ap_return_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 32'd0;
    end else begin
        if (((grp_sampleSIM_fu_274_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_return_1_preg <= grp_sampleSIM_fu_274_ap_return_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sampleSIM_fu_274_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_sampleSIM_fu_274_ap_start_reg <= 1'b1;
        end else if ((grp_sampleSIM_fu_274_ap_ready == 1'b1)) begin
            grp_sampleSIM_fu_274_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        i_fu_88 <= 9'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            i_fu_88 <= 9'd0;
        end else if (((icmp_ln64_fu_351_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            i_fu_88 <= add_ln64_fu_357_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                shl_ln_reg_742[1] <= 1'b0;
        shl_ln_reg_742[2] <= 1'b0;
        shl_ln_reg_742[3] <= 1'b0;
        shl_ln_reg_742[4] <= 1'b0;
        shl_ln_reg_742[5] <= 1'b0;
        shl_ln_reg_742[6] <= 1'b0;
        shl_ln_reg_742[7] <= 1'b0;
        shl_ln_reg_742[8] <= 1'b0;
        shl_ln_reg_742[9] <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
                        shl_ln_reg_742[9 : 1] <= shl_ln_fu_405_p3[9 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        xor_ln72_1_reg_752 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            xor_ln72_1_reg_752 <= xor_ln72_1_fu_499_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        xor_ln72_2_reg_757 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            xor_ln72_2_reg_757 <= xor_ln72_2_fu_547_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        xor_ln72_3_reg_762 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            xor_ln72_3_reg_762 <= xor_ln72_3_fu_595_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        xor_ln72_reg_747 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            xor_ln72_reg_747 <= xor_ln72_fu_451_p2;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_sampleSIM_fu_274_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_sampleSIM_fu_274_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_sampleSIM_fu_274_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_sampleSIM_fu_274_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_return_0 = grp_sampleSIM_fu_274_ap_return_0;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((grp_sampleSIM_fu_274_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_return_1 = grp_sampleSIM_fu_274_ap_return_1;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_303_p0 = xor_ln72_reg_747;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_303_p0 = xor_ln70_fu_423_p2;
    end else begin
        grp_fu_303_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_308_p0 = xor_ln72_1_reg_752;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_308_p0 = xor_ln70_1_fu_471_p2;
    end else begin
        grp_fu_308_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_313_p0 = xor_ln72_2_reg_757;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_313_p0 = xor_ln70_2_fu_519_p2;
    end else begin
        grp_fu_313_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_318_p0 = xor_ln72_3_reg_762;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_318_p0 = xor_ln70_3_fu_567_p2;
    end else begin
        grp_fu_318_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_e_1_address0 = zext_ln64_fu_379_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_1_address0 = grp_sampleSIM_fu_274_mt_rng_mt_e_1_address0;
    end else begin
        mt_rng_mt_e_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_e_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_1_ce0 = grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce0;
    end else begin
        mt_rng_mt_e_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_1_ce1 = grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce1;
    end else begin
        mt_rng_mt_e_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_e_1_d0 = add48_15_i_fu_76;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_1_d0 = grp_sampleSIM_fu_274_mt_rng_mt_e_1_d0;
    end else begin
        mt_rng_mt_e_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln64_fu_351_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mt_rng_mt_e_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_1_we0 = grp_sampleSIM_fu_274_mt_rng_mt_e_1_we0;
    end else begin
        mt_rng_mt_e_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_e_2_address0 = zext_ln64_fu_379_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_2_address0 = grp_sampleSIM_fu_274_mt_rng_mt_e_2_address0;
    end else begin
        mt_rng_mt_e_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_e_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_2_ce0 = grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce0;
    end else begin
        mt_rng_mt_e_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_2_ce1 = grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce1;
    end else begin
        mt_rng_mt_e_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_e_2_d0 = add48_26_i_fu_80;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_2_d0 = grp_sampleSIM_fu_274_mt_rng_mt_e_2_d0;
    end else begin
        mt_rng_mt_e_2_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln64_fu_351_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mt_rng_mt_e_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_2_we0 = grp_sampleSIM_fu_274_mt_rng_mt_e_2_we0;
    end else begin
        mt_rng_mt_e_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_e_3_address0 = zext_ln64_fu_379_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_3_address0 = grp_sampleSIM_fu_274_mt_rng_mt_e_3_address0;
    end else begin
        mt_rng_mt_e_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_e_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_3_ce0 = grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce0;
    end else begin
        mt_rng_mt_e_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_3_ce1 = grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce1;
    end else begin
        mt_rng_mt_e_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_e_3_d0 = add48_37_i_fu_84;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_3_d0 = grp_sampleSIM_fu_274_mt_rng_mt_e_3_d0;
    end else begin
        mt_rng_mt_e_3_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln64_fu_351_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mt_rng_mt_e_3_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_3_we0 = grp_sampleSIM_fu_274_mt_rng_mt_e_3_we0;
    end else begin
        mt_rng_mt_e_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_e_address0 = zext_ln64_fu_379_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_address0 = grp_sampleSIM_fu_274_mt_rng_mt_e_0_address0;
    end else begin
        mt_rng_mt_e_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_e_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_ce0 = grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce0;
    end else begin
        mt_rng_mt_e_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_ce1 = grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce1;
    end else begin
        mt_rng_mt_e_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_e_d0 = add484_i_fu_72;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_d0 = grp_sampleSIM_fu_274_mt_rng_mt_e_0_d0;
    end else begin
        mt_rng_mt_e_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln64_fu_351_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mt_rng_mt_e_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_e_we0 = grp_sampleSIM_fu_274_mt_rng_mt_e_0_we0;
    end else begin
        mt_rng_mt_e_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_o_1_address0 = zext_ln64_fu_379_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_1_address0 = grp_sampleSIM_fu_274_mt_rng_mt_o_1_address0;
    end else begin
        mt_rng_mt_o_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_o_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_1_ce0 = grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce0;
    end else begin
        mt_rng_mt_o_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_1_ce1 = grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce1;
    end else begin
        mt_rng_mt_o_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_o_1_d0 = add_ln70_1_fu_478_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_1_d0 = grp_sampleSIM_fu_274_mt_rng_mt_o_1_d0;
    end else begin
        mt_rng_mt_o_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln64_fu_351_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mt_rng_mt_o_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_1_we0 = grp_sampleSIM_fu_274_mt_rng_mt_o_1_we0;
    end else begin
        mt_rng_mt_o_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_o_2_address0 = zext_ln64_fu_379_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_2_address0 = grp_sampleSIM_fu_274_mt_rng_mt_o_2_address0;
    end else begin
        mt_rng_mt_o_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_o_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_2_ce0 = grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce0;
    end else begin
        mt_rng_mt_o_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_2_ce1 = grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce1;
    end else begin
        mt_rng_mt_o_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_o_2_d0 = add_ln70_2_fu_526_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_2_d0 = grp_sampleSIM_fu_274_mt_rng_mt_o_2_d0;
    end else begin
        mt_rng_mt_o_2_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln64_fu_351_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mt_rng_mt_o_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_2_we0 = grp_sampleSIM_fu_274_mt_rng_mt_o_2_we0;
    end else begin
        mt_rng_mt_o_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_o_3_address0 = zext_ln64_fu_379_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_3_address0 = grp_sampleSIM_fu_274_mt_rng_mt_o_3_address0;
    end else begin
        mt_rng_mt_o_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_o_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_3_ce0 = grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce0;
    end else begin
        mt_rng_mt_o_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_3_ce1 = grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce1;
    end else begin
        mt_rng_mt_o_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_o_3_d0 = add_ln70_3_fu_574_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_3_d0 = grp_sampleSIM_fu_274_mt_rng_mt_o_3_d0;
    end else begin
        mt_rng_mt_o_3_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln64_fu_351_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mt_rng_mt_o_3_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_3_we0 = grp_sampleSIM_fu_274_mt_rng_mt_o_3_we0;
    end else begin
        mt_rng_mt_o_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_o_address0 = zext_ln64_fu_379_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_address0 = grp_sampleSIM_fu_274_mt_rng_mt_o_0_address0;
    end else begin
        mt_rng_mt_o_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_o_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_ce0 = grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce0;
    end else begin
        mt_rng_mt_o_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_ce1 = grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce1;
    end else begin
        mt_rng_mt_o_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mt_rng_mt_o_d0 = add_ln70_fu_430_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_d0 = grp_sampleSIM_fu_274_mt_rng_mt_o_0_d0;
    end else begin
        mt_rng_mt_o_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln64_fu_351_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mt_rng_mt_o_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mt_rng_mt_o_we0 = grp_sampleSIM_fu_274_mt_rng_mt_o_0_we0;
    end else begin
        mt_rng_mt_o_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln64_fu_351_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_sampleSIM_fu_274_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln64_fu_357_p2 = (i_fu_88 + 9'd1);

assign add_ln70_1_fu_478_p2 = (grp_fu_308_p2 + zext_ln70_fu_419_p1);

assign add_ln70_2_fu_526_p2 = (grp_fu_313_p2 + zext_ln70_fu_419_p1);

assign add_ln70_3_fu_574_p2 = (grp_fu_318_p2 + zext_ln70_fu_419_p1);

assign add_ln70_fu_430_p2 = (grp_fu_303_p2 + zext_ln70_fu_419_p1);

assign add_ln72_1_fu_615_p2 = (grp_fu_303_p2 + zext_ln72_fu_611_p1);

assign add_ln72_2_fu_621_p2 = (grp_fu_308_p2 + zext_ln72_fu_611_p1);

assign add_ln72_3_fu_627_p2 = (grp_fu_313_p2 + zext_ln72_fu_611_p1);

assign add_ln72_4_fu_633_p2 = (grp_fu_318_p2 + zext_ln72_fu_611_p1);

assign add_ln72_fu_606_p2 = (shl_ln_reg_742 + 10'd2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_sampleSIM_fu_274_ap_start = grp_sampleSIM_fu_274_ap_start_reg;

assign icmp_ln64_fu_351_p2 = ((i_fu_88 == 9'd312) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_437_p4 = {{add_ln70_fu_430_p2[31:30]}};

assign lshr_ln70_1_fu_457_p4 = {{add48_15_i_fu_76[31:30]}};

assign lshr_ln70_2_fu_505_p4 = {{add48_26_i_fu_80[31:30]}};

assign lshr_ln70_3_fu_553_p4 = {{add48_37_i_fu_84[31:30]}};

assign lshr_ln72_1_fu_485_p4 = {{add_ln70_1_fu_478_p2[31:30]}};

assign lshr_ln72_2_fu_533_p4 = {{add_ln70_2_fu_526_p2[31:30]}};

assign lshr_ln72_3_fu_581_p4 = {{add_ln70_3_fu_574_p2[31:30]}};

assign lshr_ln_fu_391_p4 = {{add484_i_fu_72[31:30]}};

assign or_ln70_fu_413_p2 = (shl_ln_fu_405_p3 | 10'd1);

assign shl_ln_fu_405_p3 = {{i_fu_88}, {1'd0}};

assign xor_ln70_1_fu_471_p2 = (zext_ln70_2_fu_467_p1 ^ add48_15_i_fu_76);

assign xor_ln70_2_fu_519_p2 = (zext_ln70_3_fu_515_p1 ^ add48_26_i_fu_80);

assign xor_ln70_3_fu_567_p2 = (zext_ln70_4_fu_563_p1 ^ add48_37_i_fu_84);

assign xor_ln70_fu_423_p2 = (zext_ln70_1_fu_401_p1 ^ add484_i_fu_72);

assign xor_ln72_1_fu_499_p2 = (zext_ln72_2_fu_495_p1 ^ add_ln70_1_fu_478_p2);

assign xor_ln72_2_fu_547_p2 = (zext_ln72_3_fu_543_p1 ^ add_ln70_2_fu_526_p2);

assign xor_ln72_3_fu_595_p2 = (zext_ln72_4_fu_591_p1 ^ add_ln70_3_fu_574_p2);

assign xor_ln72_fu_451_p2 = (zext_ln72_1_fu_447_p1 ^ add_ln70_fu_430_p2);

assign zext_ln64_fu_379_p1 = i_fu_88;

assign zext_ln70_1_fu_401_p1 = lshr_ln_fu_391_p4;

assign zext_ln70_2_fu_467_p1 = lshr_ln70_1_fu_457_p4;

assign zext_ln70_3_fu_515_p1 = lshr_ln70_2_fu_505_p4;

assign zext_ln70_4_fu_563_p1 = lshr_ln70_3_fu_553_p4;

assign zext_ln70_fu_419_p1 = or_ln70_fu_413_p2;

assign zext_ln72_1_fu_447_p1 = lshr_ln1_fu_437_p4;

assign zext_ln72_2_fu_495_p1 = lshr_ln72_1_fu_485_p4;

assign zext_ln72_3_fu_543_p1 = lshr_ln72_2_fu_533_p4;

assign zext_ln72_4_fu_591_p1 = lshr_ln72_3_fu_581_p4;

assign zext_ln72_fu_611_p1 = add_ln72_fu_606_p2;

always @ (posedge ap_clk) begin
    shl_ln_reg_742[0] <= 1'b0;
end

endmodule //hestonEuro_simulation
