// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hestonEuro_sin_or_cos_float_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        t_in,
        do_cos,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [31:0] t_in;
input  [0:0] do_cos;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [3:0] ref_4oPi_table_100_address0;
reg    ref_4oPi_table_100_ce0;
wire   [99:0] ref_4oPi_table_100_q0;
wire   [7:0] second_order_float_sin_cos_K0_address0;
reg    second_order_float_sin_cos_K0_ce0;
wire   [29:0] second_order_float_sin_cos_K0_q0;
wire   [7:0] second_order_float_sin_cos_K1_address0;
reg    second_order_float_sin_cos_K1_ce0;
wire  signed [22:0] second_order_float_sin_cos_K1_q0;
wire   [7:0] second_order_float_sin_cos_K2_address0;
reg    second_order_float_sin_cos_K2_ce0;
wire  signed [14:0] second_order_float_sin_cos_K2_q0;
reg   [0:0] do_cos_read_reg_1303;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] do_cos_read_reg_1303_pp0_iter1_reg;
reg   [0:0] do_cos_read_reg_1303_pp0_iter2_reg;
reg   [0:0] do_cos_read_reg_1303_pp0_iter3_reg;
reg   [0:0] do_cos_read_reg_1303_pp0_iter4_reg;
reg   [0:0] din_sign_reg_1311;
reg   [0:0] din_sign_reg_1311_pp0_iter1_reg;
reg   [0:0] din_sign_reg_1311_pp0_iter2_reg;
wire   [7:0] din_exp_fu_310_p4;
reg   [7:0] din_exp_reg_1317;
reg   [7:0] din_exp_reg_1317_pp0_iter1_reg;
reg   [7:0] din_exp_reg_1317_pp0_iter2_reg;
wire   [22:0] din_sig_fu_320_p1;
reg   [22:0] din_sig_reg_1324;
reg   [22:0] din_sig_reg_1324_pp0_iter1_reg;
wire   [0:0] closepath_fu_324_p2;
reg   [0:0] closepath_reg_1330;
reg   [0:0] closepath_reg_1330_pp0_iter1_reg;
reg   [0:0] closepath_reg_1330_pp0_iter2_reg;
wire   [3:0] trunc_ln379_fu_359_p1;
reg   [3:0] trunc_ln379_reg_1342;
reg  signed [79:0] Med_reg_1347;
reg   [2:0] k_reg_1352;
wire   [57:0] Mx_bits_3_fu_439_p3;
reg   [57:0] Mx_bits_3_reg_1357;
wire   [5:0] Mx_zeros_fu_495_p1;
reg   [5:0] Mx_zeros_reg_1362;
wire   [0:0] icmp_ln271_1_fu_499_p2;
reg   [0:0] icmp_ln271_1_reg_1368;
reg   [0:0] icmp_ln271_1_reg_1368_pp0_iter3_reg;
reg   [0:0] icmp_ln271_1_reg_1368_pp0_iter4_reg;
wire   [7:0] Ex_1_fu_543_p2;
reg   [7:0] Ex_1_reg_1374;
reg   [7:0] Ex_1_reg_1374_pp0_iter4_reg;
wire   [21:0] B_fu_599_p1;
reg   [21:0] B_reg_1379;
wire   [0:0] cos_basis_fu_649_p3;
reg   [0:0] cos_basis_reg_1384;
reg   [0:0] cos_basis_reg_1384_pp0_iter4_reg;
wire   [28:0] Mx_1_fu_656_p3;
reg   [28:0] Mx_1_reg_1389;
reg   [28:0] Mx_1_reg_1389_pp0_iter4_reg;
reg   [14:0] B_trunc_reg_1394;
wire   [0:0] icmp_ln271_fu_865_p2;
reg   [0:0] icmp_ln271_reg_1414;
reg   [0:0] icmp_ln271_reg_1414_pp0_iter4_reg;
wire   [0:0] and_ln271_fu_870_p2;
reg   [0:0] and_ln271_reg_1419;
reg   [0:0] and_ln271_reg_1419_pp0_iter4_reg;
wire   [0:0] icmp_ln282_fu_885_p2;
reg   [0:0] icmp_ln282_reg_1425;
reg   [0:0] icmp_ln282_reg_1425_pp0_iter4_reg;
wire   [0:0] results_sign_4_fu_902_p3;
reg   [0:0] results_sign_4_reg_1432;
reg   [0:0] results_sign_4_reg_1432_pp0_iter4_reg;
wire   [29:0] add_ln32_1_fu_1000_p2;
reg  signed [29:0] add_ln32_1_reg_1437;
wire   [63:0] zext_ln378_fu_354_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln28_fu_699_p1;
wire   [21:0] mul_ln29_fu_286_p1;
wire   [28:0] mul_ln32_fu_290_p1;
wire   [23:0] h_fu_294_p1;
wire   [31:0] data_fu_298_p1;
wire   [7:0] add_ln376_fu_330_p2;
wire   [7:0] addr_fu_336_p3;
wire   [3:0] lshr_ln_fu_344_p4;
wire   [99:0] zext_ln379_fu_363_p1;
wire   [99:0] shl_ln379_fu_366_p2;
wire   [23:0] X_fu_382_p3;
wire   [79:0] h_fu_294_p2;
wire   [0:0] tmp_fu_414_p3;
wire   [0:0] xor_ln451_fu_422_p2;
wire   [57:0] Mx_bits_fu_394_p4;
wire   [0:0] and_ln451_fu_427_p2;
wire   [57:0] Mx_bits_1_fu_433_p2;
wire   [28:0] tmp_2_fu_447_p4;
wire   [29:0] t_fu_457_p3;
reg   [29:0] tmp_8_fu_465_p4;
wire   [30:0] tmp_9_fu_475_p3;
wire  signed [31:0] sext_ln75_fu_483_p1;
reg   [31:0] tmp_s_fu_487_p3;
wire   [7:0] Ex_fu_504_p2;
wire   [57:0] zext_ln504_fu_525_p1;
wire   [57:0] shl_ln504_fu_528_p2;
wire   [7:0] select_ln453_fu_509_p3;
wire   [7:0] zext_ln505_fu_522_p1;
wire   [0:0] tmp_6_fu_549_p3;
wire   [7:0] sub_ln506_fu_557_p2;
wire   [7:0] select_ln506_fu_563_p3;
wire   [28:0] Mx_fu_533_p4;
wire   [31:0] zext_ln506_fu_575_p1;
wire   [31:0] zext_ln506_1_fu_571_p1;
wire   [31:0] lshr_ln506_fu_579_p2;
wire   [31:0] shl_ln506_fu_585_p2;
wire   [31:0] select_ln506_1_fu_591_p3;
wire   [0:0] tmp_1_fu_603_p17;
wire   [2:0] k_1_fu_516_p3;
wire   [0:0] tmp_1_fu_603_p19;
wire   [0:0] xor_ln242_fu_643_p2;
wire   [0:0] sin_basis_fu_684_p3;
wire   [6:0] tmp_3_fu_664_p4;
wire   [7:0] A_fu_691_p3;
wire   [0:0] tmp_11_fu_713_p33;
wire   [3:0] index_fu_706_p3;
wire   [0:0] tmp_12_fu_785_p33;
wire   [0:0] tmp_11_fu_713_p35;
wire   [0:0] tmp_12_fu_785_p35;
wire   [0:0] xor_ln278_fu_875_p2;
wire   [0:0] results_sign_fu_857_p3;
wire   [0:0] xor_ln282_fu_890_p2;
wire   [0:0] results_sign_2_fu_880_p2;
wire   [0:0] results_sign_3_fu_896_p2;
wire   [14:0] mul_ln23_fu_913_p0;
wire   [29:0] zext_ln23_fu_910_p1;
wire   [14:0] mul_ln23_fu_913_p1;
wire   [29:0] mul_ln23_fu_913_p2;
wire   [14:0] B_squared_fu_919_p4;
wire   [44:0] mul_ln29_fu_286_p2;
wire   [14:0] mul_ln30_fu_966_p0;
wire   [29:0] mul_ln30_fu_966_p2;
wire   [28:0] t1_fu_933_p4;
wire   [21:0] trunc_ln_fu_952_p4;
wire  signed [29:0] sext_ln32_fu_982_p1;
wire  signed [29:0] sext_ln32_1_fu_986_p1;
wire   [13:0] trunc_ln1_fu_972_p4;
wire   [29:0] add_ln32_fu_990_p2;
wire  signed [29:0] sext_ln32_2_fu_996_p1;
wire   [57:0] mul_ln32_fu_290_p2;
wire   [7:0] Ex_2_fu_1006_p3;
wire   [15:0] tmp_4_fu_1034_p4;
wire   [12:0] tmp_7_fu_1052_p4;
wire   [31:0] out_bits_fu_1044_p3;
reg   [31:0] tmp_5_fu_1070_p4;
wire   [31:0] out_bits_2_fu_1062_p3;
reg   [31:0] tmp_10_fu_1088_p4;
wire   [28:0] result_fu_1020_p4;
wire   [31:0] zext_ln291_fu_1106_p1;
reg   [31:0] c_fu_1080_p3;
wire   [31:0] shl_ln291_fu_1110_p2;
reg   [31:0] c_1_fu_1098_p3;
wire   [27:0] in_shift_1_fu_1116_p1;
wire   [31:0] zext_ln291_1_fu_1132_p1;
wire   [0:0] icmp_ln292_fu_1120_p2;
wire   [31:0] add_ln290_fu_1126_p2;
wire  signed [8:0] sext_ln252_fu_1030_p1;
wire   [8:0] add_ln300_fu_1150_p2;
wire  signed [31:0] sext_ln300_fu_1156_p1;
wire   [31:0] shift_1_fu_1142_p3;
wire   [31:0] newexp_fu_1160_p2;
wire   [0:0] tmp_15_fu_1166_p3;
wire   [0:0] icmp_ln306_fu_1174_p2;
wire   [31:0] shl_ln291_1_fu_1136_p2;
wire   [22:0] tmp_13_fu_1186_p4;
wire   [22:0] tmp_14_fu_1196_p4;
wire   [0:0] or_ln306_fu_1180_p2;
wire   [0:0] or_ln282_fu_1232_p2;
wire   [7:0] select_ln282_fu_1225_p3;
wire   [7:0] empty_fu_1214_p1;
wire   [7:0] select_ln259_fu_1218_p3;
wire   [7:0] results_exp_fu_1237_p3;
wire   [0:0] and_ln271_1_fu_1252_p2;
wire   [0:0] xor_ln271_fu_1256_p2;
wire   [22:0] select_ln292_fu_1206_p3;
wire   [0:0] or_ln271_fu_1270_p2;
wire   [22:0] select_ln271_3_fu_1262_p3;
wire   [22:0] select_ln271_fu_1274_p3;
wire   [7:0] results_exp_1_fu_1245_p3;
wire   [22:0] results_sig_fu_1282_p3;
wire   [31:0] t_2_fu_1290_p4;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
reg    ap_reset_start_pp0;
wire    ap_enable_pp0;
wire   [79:0] h_fu_294_p10;
wire   [44:0] mul_ln29_fu_286_p10;
wire   [29:0] mul_ln30_fu_966_p00;
wire   [57:0] mul_ln32_fu_290_p10;
wire   [2:0] tmp_1_fu_603_p1;
wire   [2:0] tmp_1_fu_603_p3;
wire   [2:0] tmp_1_fu_603_p5;
wire   [2:0] tmp_1_fu_603_p7;
wire  signed [2:0] tmp_1_fu_603_p9;
wire  signed [2:0] tmp_1_fu_603_p11;
wire  signed [2:0] tmp_1_fu_603_p13;
wire  signed [2:0] tmp_1_fu_603_p15;
wire   [3:0] tmp_11_fu_713_p1;
wire   [3:0] tmp_11_fu_713_p3;
wire   [3:0] tmp_11_fu_713_p5;
wire   [3:0] tmp_11_fu_713_p7;
wire   [3:0] tmp_11_fu_713_p9;
wire   [3:0] tmp_11_fu_713_p11;
wire   [3:0] tmp_11_fu_713_p13;
wire   [3:0] tmp_11_fu_713_p15;
wire  signed [3:0] tmp_11_fu_713_p17;
wire  signed [3:0] tmp_11_fu_713_p19;
wire  signed [3:0] tmp_11_fu_713_p21;
wire  signed [3:0] tmp_11_fu_713_p23;
wire  signed [3:0] tmp_11_fu_713_p25;
wire  signed [3:0] tmp_11_fu_713_p27;
wire  signed [3:0] tmp_11_fu_713_p29;
wire  signed [3:0] tmp_11_fu_713_p31;
wire   [3:0] tmp_12_fu_785_p1;
wire   [3:0] tmp_12_fu_785_p3;
wire   [3:0] tmp_12_fu_785_p5;
wire   [3:0] tmp_12_fu_785_p7;
wire   [3:0] tmp_12_fu_785_p9;
wire   [3:0] tmp_12_fu_785_p11;
wire   [3:0] tmp_12_fu_785_p13;
wire   [3:0] tmp_12_fu_785_p15;
wire  signed [3:0] tmp_12_fu_785_p17;
wire  signed [3:0] tmp_12_fu_785_p19;
wire  signed [3:0] tmp_12_fu_785_p21;
wire  signed [3:0] tmp_12_fu_785_p23;
wire  signed [3:0] tmp_12_fu_785_p25;
wire  signed [3:0] tmp_12_fu_785_p27;
wire  signed [3:0] tmp_12_fu_785_p29;
wire  signed [3:0] tmp_12_fu_785_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 do_cos_read_reg_1303 = 1'd0;
#0 do_cos_read_reg_1303_pp0_iter1_reg = 1'd0;
#0 do_cos_read_reg_1303_pp0_iter2_reg = 1'd0;
#0 do_cos_read_reg_1303_pp0_iter3_reg = 1'd0;
#0 do_cos_read_reg_1303_pp0_iter4_reg = 1'd0;
#0 din_sign_reg_1311 = 1'd0;
#0 din_sign_reg_1311_pp0_iter1_reg = 1'd0;
#0 din_sign_reg_1311_pp0_iter2_reg = 1'd0;
#0 din_exp_reg_1317 = 8'd0;
#0 din_exp_reg_1317_pp0_iter1_reg = 8'd0;
#0 din_exp_reg_1317_pp0_iter2_reg = 8'd0;
#0 din_sig_reg_1324 = 23'd0;
#0 din_sig_reg_1324_pp0_iter1_reg = 23'd0;
#0 closepath_reg_1330 = 1'd0;
#0 closepath_reg_1330_pp0_iter1_reg = 1'd0;
#0 closepath_reg_1330_pp0_iter2_reg = 1'd0;
#0 trunc_ln379_reg_1342 = 4'd0;
#0 Med_reg_1347 = 80'd0;
#0 k_reg_1352 = 3'd0;
#0 Mx_bits_3_reg_1357 = 58'd0;
#0 Mx_zeros_reg_1362 = 6'd0;
#0 icmp_ln271_1_reg_1368 = 1'd0;
#0 icmp_ln271_1_reg_1368_pp0_iter3_reg = 1'd0;
#0 icmp_ln271_1_reg_1368_pp0_iter4_reg = 1'd0;
#0 Ex_1_reg_1374 = 8'd0;
#0 Ex_1_reg_1374_pp0_iter4_reg = 8'd0;
#0 B_reg_1379 = 22'd0;
#0 cos_basis_reg_1384 = 1'd0;
#0 cos_basis_reg_1384_pp0_iter4_reg = 1'd0;
#0 Mx_1_reg_1389 = 29'd0;
#0 Mx_1_reg_1389_pp0_iter4_reg = 29'd0;
#0 B_trunc_reg_1394 = 15'd0;
#0 icmp_ln271_reg_1414 = 1'd0;
#0 icmp_ln271_reg_1414_pp0_iter4_reg = 1'd0;
#0 and_ln271_reg_1419 = 1'd0;
#0 and_ln271_reg_1419_pp0_iter4_reg = 1'd0;
#0 icmp_ln282_reg_1425 = 1'd0;
#0 icmp_ln282_reg_1425_pp0_iter4_reg = 1'd0;
#0 results_sign_4_reg_1432 = 1'd0;
#0 results_sign_4_reg_1432_pp0_iter4_reg = 1'd0;
#0 add_ln32_1_reg_1437 = 30'd0;
end

hestonEuro_sin_or_cos_float_s_ref_4oPi_table_100_ROM_1P_LUTRAM_1R #(
    .DataWidth( 100 ),
    .AddressRange( 13 ),
    .AddressWidth( 4 ))
ref_4oPi_table_100_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ref_4oPi_table_100_address0),
    .ce0(ref_4oPi_table_100_ce0),
    .q0(ref_4oPi_table_100_q0)
);

hestonEuro_sin_or_cos_float_s_second_order_float_sin_cos_K0_ROM_1P_LUTRAM_1R #(
    .DataWidth( 30 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K0_address0),
    .ce0(second_order_float_sin_cos_K0_ce0),
    .q0(second_order_float_sin_cos_K0_q0)
);

hestonEuro_sin_or_cos_float_s_second_order_float_sin_cos_K1_ROM_1P_LUTRAM_1R #(
    .DataWidth( 23 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K1_address0),
    .ce0(second_order_float_sin_cos_K1_ce0),
    .q0(second_order_float_sin_cos_K1_q0)
);

hestonEuro_sin_or_cos_float_s_second_order_float_sin_cos_K2_ROM_1P_LUTRAM_1R #(
    .DataWidth( 15 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K2_address0),
    .ce0(second_order_float_sin_cos_K2_ce0),
    .q0(second_order_float_sin_cos_K2_q0)
);

hestonEuro_mul_23s_22ns_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 45 ))
mul_23s_22ns_45_1_1_U2(
    .din0(second_order_float_sin_cos_K1_q0),
    .din1(mul_ln29_fu_286_p1),
    .dout(mul_ln29_fu_286_p2)
);

hestonEuro_mul_30s_29ns_58_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 58 ))
mul_30s_29ns_58_1_1_U3(
    .din0(add_ln32_1_reg_1437),
    .din1(mul_ln32_fu_290_p1),
    .dout(mul_ln32_fu_290_p2)
);

hestonEuro_mul_80s_24ns_80_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 80 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 80 ))
mul_80s_24ns_80_1_1_U4(
    .din0(Med_reg_1347),
    .din1(h_fu_294_p1),
    .dout(h_fu_294_p2)
);

hestonEuro_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U5(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .def(tmp_1_fu_603_p17),
    .sel(k_1_fu_516_p3),
    .dout(tmp_1_fu_603_p19)
);

hestonEuro_sparsemux_33_4_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 1 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 1 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 1 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 1 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 1 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 1 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 1 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 1 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
sparsemux_33_4_1_1_1_U6(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd0),
    .din9(1'd1),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd0),
    .din15(1'd0),
    .def(tmp_11_fu_713_p33),
    .sel(index_fu_706_p3),
    .dout(tmp_11_fu_713_p35)
);

hestonEuro_sparsemux_33_4_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 1 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 1 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 1 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 1 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 1 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 1 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 1 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 1 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
sparsemux_33_4_1_1_1_U7(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd0),
    .din7(1'd1),
    .din8(1'd1),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd0),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .def(tmp_12_fu_785_p33),
    .sel(index_fu_706_p3),
    .dout(tmp_12_fu_785_p35)
);

hestonEuro_mul_15ns_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_15ns_15ns_30_1_1_U8(
    .din0(mul_ln23_fu_913_p0),
    .din1(mul_ln23_fu_913_p1),
    .dout(mul_ln23_fu_913_p2)
);

hestonEuro_mul_15ns_15s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_15ns_15s_30_1_1_U9(
    .din0(mul_ln30_fu_966_p0),
    .din1(second_order_float_sin_cos_K2_q0),
    .dout(mul_ln30_fu_966_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_reg_1379 <= 22'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            B_reg_1379 <= B_fu_599_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_trunc_reg_1394 <= 15'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            B_trunc_reg_1394 <= {{select_ln506_1_fu_591_p3[21:7]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        Ex_1_reg_1374 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            Ex_1_reg_1374 <= Ex_1_fu_543_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        Ex_1_reg_1374_pp0_iter4_reg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            Ex_1_reg_1374_pp0_iter4_reg <= Ex_1_reg_1374;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        Med_reg_1347 <= 80'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            Med_reg_1347 <= {{shl_ln379_fu_366_p2[99:20]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        Mx_1_reg_1389 <= 29'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            Mx_1_reg_1389 <= Mx_1_fu_656_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        Mx_1_reg_1389_pp0_iter4_reg <= 29'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            Mx_1_reg_1389_pp0_iter4_reg <= Mx_1_reg_1389;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        Mx_bits_3_reg_1357 <= 58'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            Mx_bits_3_reg_1357 <= Mx_bits_3_fu_439_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        Mx_zeros_reg_1362 <= 6'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            Mx_zeros_reg_1362 <= Mx_zeros_fu_495_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        add_ln32_1_reg_1437 <= 30'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            add_ln32_1_reg_1437 <= add_ln32_1_fu_1000_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        and_ln271_reg_1419 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            and_ln271_reg_1419 <= and_ln271_fu_870_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        and_ln271_reg_1419_pp0_iter4_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            and_ln271_reg_1419_pp0_iter4_reg <= and_ln271_reg_1419;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        closepath_reg_1330 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            closepath_reg_1330 <= closepath_fu_324_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        closepath_reg_1330_pp0_iter1_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            closepath_reg_1330_pp0_iter1_reg <= closepath_reg_1330;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        closepath_reg_1330_pp0_iter2_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            closepath_reg_1330_pp0_iter2_reg <= closepath_reg_1330_pp0_iter1_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        cos_basis_reg_1384 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            cos_basis_reg_1384 <= cos_basis_fu_649_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        cos_basis_reg_1384_pp0_iter4_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            cos_basis_reg_1384_pp0_iter4_reg <= cos_basis_reg_1384;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        din_exp_reg_1317 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            din_exp_reg_1317 <= {{data_fu_298_p1[30:23]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        din_exp_reg_1317_pp0_iter1_reg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            din_exp_reg_1317_pp0_iter1_reg <= din_exp_reg_1317;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        din_exp_reg_1317_pp0_iter2_reg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            din_exp_reg_1317_pp0_iter2_reg <= din_exp_reg_1317_pp0_iter1_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        din_sig_reg_1324 <= 23'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            din_sig_reg_1324 <= din_sig_fu_320_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        din_sig_reg_1324_pp0_iter1_reg <= 23'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            din_sig_reg_1324_pp0_iter1_reg <= din_sig_reg_1324;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        din_sign_reg_1311 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            din_sign_reg_1311 <= data_fu_298_p1[32'd31];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        din_sign_reg_1311_pp0_iter1_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            din_sign_reg_1311_pp0_iter1_reg <= din_sign_reg_1311;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        din_sign_reg_1311_pp0_iter2_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            din_sign_reg_1311_pp0_iter2_reg <= din_sign_reg_1311_pp0_iter1_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        do_cos_read_reg_1303 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            do_cos_read_reg_1303 <= do_cos;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        do_cos_read_reg_1303_pp0_iter1_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            do_cos_read_reg_1303_pp0_iter1_reg <= do_cos_read_reg_1303;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        do_cos_read_reg_1303_pp0_iter2_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            do_cos_read_reg_1303_pp0_iter2_reg <= do_cos_read_reg_1303_pp0_iter1_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        do_cos_read_reg_1303_pp0_iter3_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            do_cos_read_reg_1303_pp0_iter3_reg <= do_cos_read_reg_1303_pp0_iter2_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        do_cos_read_reg_1303_pp0_iter4_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            do_cos_read_reg_1303_pp0_iter4_reg <= do_cos_read_reg_1303_pp0_iter3_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln271_1_reg_1368 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            icmp_ln271_1_reg_1368 <= icmp_ln271_1_fu_499_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln271_1_reg_1368_pp0_iter3_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            icmp_ln271_1_reg_1368_pp0_iter3_reg <= icmp_ln271_1_reg_1368;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln271_1_reg_1368_pp0_iter4_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            icmp_ln271_1_reg_1368_pp0_iter4_reg <= icmp_ln271_1_reg_1368_pp0_iter3_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln271_reg_1414 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            icmp_ln271_reg_1414 <= icmp_ln271_fu_865_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln271_reg_1414_pp0_iter4_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            icmp_ln271_reg_1414_pp0_iter4_reg <= icmp_ln271_reg_1414;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln282_reg_1425 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            icmp_ln282_reg_1425 <= icmp_ln282_fu_885_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln282_reg_1425_pp0_iter4_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            icmp_ln282_reg_1425_pp0_iter4_reg <= icmp_ln282_reg_1425;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        k_reg_1352 <= 3'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            k_reg_1352 <= {{h_fu_294_p2[79:77]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        results_sign_4_reg_1432 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            results_sign_4_reg_1432 <= results_sign_4_fu_902_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        results_sign_4_reg_1432_pp0_iter4_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
            results_sign_4_reg_1432_pp0_iter4_reg <= results_sign_4_reg_1432;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln379_reg_1342 <= 4'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            trunc_ln379_reg_1342 <= trunc_ln379_fu_359_p1;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to4 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to4 == 1'b1) & (ap_start == 1'b1))) begin
        ap_reset_start_pp0 = 1'b1;
    end else begin
        ap_reset_start_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_4oPi_table_100_ce0 = 1'b1;
    end else begin
        ref_4oPi_table_100_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_ce))) begin
        second_order_float_sin_cos_K0_ce0 = 1'b1;
    end else begin
        second_order_float_sin_cos_K0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_ce))) begin
        second_order_float_sin_cos_K1_ce0 = 1'b1;
    end else begin
        second_order_float_sin_cos_K1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_ce))) begin
        second_order_float_sin_cos_K2_ce0 = 1'b1;
    end else begin
        second_order_float_sin_cos_K2_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_fu_691_p3 = {{sin_basis_fu_684_p3}, {tmp_3_fu_664_p4}};

assign B_fu_599_p1 = select_ln506_1_fu_591_p3[21:0];

assign B_squared_fu_919_p4 = {{mul_ln23_fu_913_p2[29:15]}};

assign Ex_1_fu_543_p2 = (select_ln453_fu_509_p3 - zext_ln505_fu_522_p1);

assign Ex_2_fu_1006_p3 = ((cos_basis_reg_1384_pp0_iter4_reg[0:0] == 1'b1) ? 8'd0 : Ex_1_reg_1374_pp0_iter4_reg);

assign Ex_fu_504_p2 = ($signed(din_exp_reg_1317_pp0_iter2_reg) + $signed(8'd131));

assign Mx_1_fu_656_p3 = ((cos_basis_fu_649_p3[0:0] == 1'b1) ? 29'd536870911 : Mx_fu_533_p4);

assign Mx_bits_1_fu_433_p2 = (58'd0 - Mx_bits_fu_394_p4);

assign Mx_bits_3_fu_439_p3 = ((and_ln451_fu_427_p2[0:0] == 1'b1) ? Mx_bits_1_fu_433_p2 : Mx_bits_fu_394_p4);

assign Mx_bits_fu_394_p4 = {{h_fu_294_p2[76:19]}};

assign Mx_fu_533_p4 = {{shl_ln504_fu_528_p2[57:29]}};

assign Mx_zeros_fu_495_p1 = tmp_s_fu_487_p3[5:0];

assign X_fu_382_p3 = {{1'd1}, {din_sig_reg_1324_pp0_iter1_reg}};

assign add_ln290_fu_1126_p2 = (c_1_fu_1098_p3 + 32'd16);

assign add_ln300_fu_1150_p2 = ($signed(sext_ln252_fu_1030_p1) + $signed(9'd127));

assign add_ln32_1_fu_1000_p2 = ($signed(add_ln32_fu_990_p2) + $signed(sext_ln32_2_fu_996_p1));

assign add_ln32_fu_990_p2 = ($signed(sext_ln32_fu_982_p1) + $signed(sext_ln32_1_fu_986_p1));

assign add_ln376_fu_330_p2 = ($signed(din_exp_fu_310_p4) + $signed(8'd194));

assign addr_fu_336_p3 = ((closepath_fu_324_p2[0:0] == 1'b1) ? 8'd63 : add_ln376_fu_330_p2);

assign and_ln271_1_fu_1252_p2 = (icmp_ln271_reg_1414_pp0_iter4_reg & icmp_ln271_1_reg_1368_pp0_iter4_reg);

assign and_ln271_fu_870_p2 = (icmp_ln271_fu_865_p2 & icmp_ln271_1_reg_1368);

assign and_ln451_fu_427_p2 = (xor_ln451_fu_422_p2 & tmp_fu_414_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = t_2_fu_1290_p4;


always @ (tmp_10_fu_1088_p4) begin
    if (tmp_10_fu_1088_p4[0] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd0;
    end else if (tmp_10_fu_1088_p4[1] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd1;
    end else if (tmp_10_fu_1088_p4[2] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd2;
    end else if (tmp_10_fu_1088_p4[3] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd3;
    end else if (tmp_10_fu_1088_p4[4] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd4;
    end else if (tmp_10_fu_1088_p4[5] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd5;
    end else if (tmp_10_fu_1088_p4[6] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd6;
    end else if (tmp_10_fu_1088_p4[7] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd7;
    end else if (tmp_10_fu_1088_p4[8] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd8;
    end else if (tmp_10_fu_1088_p4[9] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd9;
    end else if (tmp_10_fu_1088_p4[10] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd10;
    end else if (tmp_10_fu_1088_p4[11] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd11;
    end else if (tmp_10_fu_1088_p4[12] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd12;
    end else if (tmp_10_fu_1088_p4[13] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd13;
    end else if (tmp_10_fu_1088_p4[14] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd14;
    end else if (tmp_10_fu_1088_p4[15] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd15;
    end else if (tmp_10_fu_1088_p4[16] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd16;
    end else if (tmp_10_fu_1088_p4[17] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd17;
    end else if (tmp_10_fu_1088_p4[18] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd18;
    end else if (tmp_10_fu_1088_p4[19] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd19;
    end else if (tmp_10_fu_1088_p4[20] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd20;
    end else if (tmp_10_fu_1088_p4[21] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd21;
    end else if (tmp_10_fu_1088_p4[22] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd22;
    end else if (tmp_10_fu_1088_p4[23] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd23;
    end else if (tmp_10_fu_1088_p4[24] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd24;
    end else if (tmp_10_fu_1088_p4[25] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd25;
    end else if (tmp_10_fu_1088_p4[26] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd26;
    end else if (tmp_10_fu_1088_p4[27] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd27;
    end else if (tmp_10_fu_1088_p4[28] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd28;
    end else if (tmp_10_fu_1088_p4[29] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd29;
    end else if (tmp_10_fu_1088_p4[30] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd30;
    end else if (tmp_10_fu_1088_p4[31] == 1'b1) begin
        c_1_fu_1098_p3 = 32'd31;
    end else begin
        c_1_fu_1098_p3 = 32'd32;
    end
end


always @ (tmp_5_fu_1070_p4) begin
    if (tmp_5_fu_1070_p4[0] == 1'b1) begin
        c_fu_1080_p3 = 32'd0;
    end else if (tmp_5_fu_1070_p4[1] == 1'b1) begin
        c_fu_1080_p3 = 32'd1;
    end else if (tmp_5_fu_1070_p4[2] == 1'b1) begin
        c_fu_1080_p3 = 32'd2;
    end else if (tmp_5_fu_1070_p4[3] == 1'b1) begin
        c_fu_1080_p3 = 32'd3;
    end else if (tmp_5_fu_1070_p4[4] == 1'b1) begin
        c_fu_1080_p3 = 32'd4;
    end else if (tmp_5_fu_1070_p4[5] == 1'b1) begin
        c_fu_1080_p3 = 32'd5;
    end else if (tmp_5_fu_1070_p4[6] == 1'b1) begin
        c_fu_1080_p3 = 32'd6;
    end else if (tmp_5_fu_1070_p4[7] == 1'b1) begin
        c_fu_1080_p3 = 32'd7;
    end else if (tmp_5_fu_1070_p4[8] == 1'b1) begin
        c_fu_1080_p3 = 32'd8;
    end else if (tmp_5_fu_1070_p4[9] == 1'b1) begin
        c_fu_1080_p3 = 32'd9;
    end else if (tmp_5_fu_1070_p4[10] == 1'b1) begin
        c_fu_1080_p3 = 32'd10;
    end else if (tmp_5_fu_1070_p4[11] == 1'b1) begin
        c_fu_1080_p3 = 32'd11;
    end else if (tmp_5_fu_1070_p4[12] == 1'b1) begin
        c_fu_1080_p3 = 32'd12;
    end else if (tmp_5_fu_1070_p4[13] == 1'b1) begin
        c_fu_1080_p3 = 32'd13;
    end else if (tmp_5_fu_1070_p4[14] == 1'b1) begin
        c_fu_1080_p3 = 32'd14;
    end else if (tmp_5_fu_1070_p4[15] == 1'b1) begin
        c_fu_1080_p3 = 32'd15;
    end else if (tmp_5_fu_1070_p4[16] == 1'b1) begin
        c_fu_1080_p3 = 32'd16;
    end else if (tmp_5_fu_1070_p4[17] == 1'b1) begin
        c_fu_1080_p3 = 32'd17;
    end else if (tmp_5_fu_1070_p4[18] == 1'b1) begin
        c_fu_1080_p3 = 32'd18;
    end else if (tmp_5_fu_1070_p4[19] == 1'b1) begin
        c_fu_1080_p3 = 32'd19;
    end else if (tmp_5_fu_1070_p4[20] == 1'b1) begin
        c_fu_1080_p3 = 32'd20;
    end else if (tmp_5_fu_1070_p4[21] == 1'b1) begin
        c_fu_1080_p3 = 32'd21;
    end else if (tmp_5_fu_1070_p4[22] == 1'b1) begin
        c_fu_1080_p3 = 32'd22;
    end else if (tmp_5_fu_1070_p4[23] == 1'b1) begin
        c_fu_1080_p3 = 32'd23;
    end else if (tmp_5_fu_1070_p4[24] == 1'b1) begin
        c_fu_1080_p3 = 32'd24;
    end else if (tmp_5_fu_1070_p4[25] == 1'b1) begin
        c_fu_1080_p3 = 32'd25;
    end else if (tmp_5_fu_1070_p4[26] == 1'b1) begin
        c_fu_1080_p3 = 32'd26;
    end else if (tmp_5_fu_1070_p4[27] == 1'b1) begin
        c_fu_1080_p3 = 32'd27;
    end else if (tmp_5_fu_1070_p4[28] == 1'b1) begin
        c_fu_1080_p3 = 32'd28;
    end else if (tmp_5_fu_1070_p4[29] == 1'b1) begin
        c_fu_1080_p3 = 32'd29;
    end else if (tmp_5_fu_1070_p4[30] == 1'b1) begin
        c_fu_1080_p3 = 32'd30;
    end else if (tmp_5_fu_1070_p4[31] == 1'b1) begin
        c_fu_1080_p3 = 32'd31;
    end else begin
        c_fu_1080_p3 = 32'd32;
    end
end

assign closepath_fu_324_p2 = ((din_exp_fu_310_p4 < 8'd126) ? 1'b1 : 1'b0);

assign cos_basis_fu_649_p3 = ((do_cos_read_reg_1303_pp0_iter2_reg[0:0] == 1'b1) ? xor_ln242_fu_643_p2 : tmp_1_fu_603_p19);

assign data_fu_298_p1 = t_in;

assign din_exp_fu_310_p4 = {{data_fu_298_p1[30:23]}};

assign din_sig_fu_320_p1 = data_fu_298_p1[22:0];

assign empty_fu_1214_p1 = newexp_fu_1160_p2[7:0];

assign h_fu_294_p1 = h_fu_294_p10;

assign h_fu_294_p10 = X_fu_382_p3;

assign icmp_ln271_1_fu_499_p2 = ((din_sig_reg_1324_pp0_iter1_reg == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_865_p2 = ((din_exp_reg_1317_pp0_iter2_reg == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln282_fu_885_p2 = ((din_exp_reg_1317_pp0_iter2_reg == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln292_fu_1120_p2 = ((c_fu_1080_p3 == 32'd16) ? 1'b1 : 1'b0);

assign icmp_ln306_fu_1174_p2 = ((result_fu_1020_p4 == 29'd0) ? 1'b1 : 1'b0);

assign in_shift_1_fu_1116_p1 = shl_ln291_fu_1110_p2[27:0];

assign index_fu_706_p3 = {{din_sign_reg_1311_pp0_iter2_reg}, {k_1_fu_516_p3}};

assign k_1_fu_516_p3 = ((closepath_reg_1330_pp0_iter2_reg[0:0] == 1'b1) ? 3'd0 : k_reg_1352);

assign lshr_ln506_fu_579_p2 = zext_ln506_fu_575_p1 >> zext_ln506_1_fu_571_p1;

assign lshr_ln_fu_344_p4 = {{addr_fu_336_p3[7:4]}};

assign mul_ln23_fu_913_p0 = zext_ln23_fu_910_p1;

assign mul_ln23_fu_913_p1 = zext_ln23_fu_910_p1;

assign mul_ln29_fu_286_p1 = mul_ln29_fu_286_p10;

assign mul_ln29_fu_286_p10 = B_reg_1379;

assign mul_ln30_fu_966_p0 = mul_ln30_fu_966_p00;

assign mul_ln30_fu_966_p00 = B_squared_fu_919_p4;

assign mul_ln32_fu_290_p1 = mul_ln32_fu_290_p10;

assign mul_ln32_fu_290_p10 = Mx_1_reg_1389_pp0_iter4_reg;

assign newexp_fu_1160_p2 = ($signed(sext_ln300_fu_1156_p1) - $signed(shift_1_fu_1142_p3));

assign or_ln271_fu_1270_p2 = (icmp_ln282_reg_1425_pp0_iter4_reg | and_ln271_reg_1419_pp0_iter4_reg);

assign or_ln282_fu_1232_p2 = (or_ln306_fu_1180_p2 | icmp_ln282_reg_1425_pp0_iter4_reg);

assign or_ln306_fu_1180_p2 = (tmp_15_fu_1166_p3 | icmp_ln306_fu_1174_p2);

assign out_bits_2_fu_1062_p3 = {{tmp_7_fu_1052_p4}, {19'd262144}};

assign out_bits_fu_1044_p3 = {{tmp_4_fu_1034_p4}, {16'd32768}};

assign ref_4oPi_table_100_address0 = zext_ln378_fu_354_p1;

assign result_fu_1020_p4 = {{mul_ln32_fu_290_p2[57:29]}};

assign results_exp_1_fu_1245_p3 = ((and_ln271_reg_1419_pp0_iter4_reg[0:0] == 1'b1) ? select_ln259_fu_1218_p3 : results_exp_fu_1237_p3);

assign results_exp_fu_1237_p3 = ((or_ln282_fu_1232_p2[0:0] == 1'b1) ? select_ln282_fu_1225_p3 : empty_fu_1214_p1);

assign results_sig_fu_1282_p3 = ((or_ln271_fu_1270_p2[0:0] == 1'b1) ? select_ln271_3_fu_1262_p3 : select_ln271_fu_1274_p3);

assign results_sign_2_fu_880_p2 = (xor_ln278_fu_875_p2 & din_sign_reg_1311_pp0_iter2_reg);

assign results_sign_3_fu_896_p2 = (xor_ln282_fu_890_p2 & results_sign_fu_857_p3);

assign results_sign_4_fu_902_p3 = ((and_ln271_fu_870_p2[0:0] == 1'b1) ? results_sign_2_fu_880_p2 : results_sign_3_fu_896_p2);

assign results_sign_fu_857_p3 = ((cos_basis_fu_649_p3[0:0] == 1'b1) ? tmp_11_fu_713_p35 : tmp_12_fu_785_p35);

assign second_order_float_sin_cos_K0_address0 = zext_ln28_fu_699_p1;

assign second_order_float_sin_cos_K1_address0 = zext_ln28_fu_699_p1;

assign second_order_float_sin_cos_K2_address0 = zext_ln28_fu_699_p1;

assign select_ln259_fu_1218_p3 = ((do_cos_read_reg_1303_pp0_iter4_reg[0:0] == 1'b1) ? 8'd127 : 8'd0);

assign select_ln271_3_fu_1262_p3 = ((xor_ln271_fu_1256_p2[0:0] == 1'b1) ? 23'd8388607 : 23'd0);

assign select_ln271_fu_1274_p3 = ((or_ln306_fu_1180_p2[0:0] == 1'b1) ? 23'd0 : select_ln292_fu_1206_p3);

assign select_ln282_fu_1225_p3 = ((icmp_ln282_reg_1425_pp0_iter4_reg[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln292_fu_1206_p3 = ((icmp_ln292_fu_1120_p2[0:0] == 1'b1) ? tmp_13_fu_1186_p4 : tmp_14_fu_1196_p4);

assign select_ln453_fu_509_p3 = ((closepath_reg_1330_pp0_iter2_reg[0:0] == 1'b1) ? Ex_fu_504_p2 : 8'd0);

assign select_ln506_1_fu_591_p3 = ((tmp_6_fu_549_p3[0:0] == 1'b1) ? lshr_ln506_fu_579_p2 : shl_ln506_fu_585_p2);

assign select_ln506_fu_563_p3 = ((tmp_6_fu_549_p3[0:0] == 1'b1) ? sub_ln506_fu_557_p2 : Ex_1_fu_543_p2);

assign sext_ln252_fu_1030_p1 = $signed(Ex_2_fu_1006_p3);

assign sext_ln300_fu_1156_p1 = $signed(add_ln300_fu_1150_p2);

assign sext_ln32_1_fu_986_p1 = $signed(trunc_ln_fu_952_p4);

assign sext_ln32_2_fu_996_p1 = $signed(trunc_ln1_fu_972_p4);

assign sext_ln32_fu_982_p1 = $signed(t1_fu_933_p4);

assign sext_ln75_fu_483_p1 = $signed(tmp_9_fu_475_p3);

assign shift_1_fu_1142_p3 = ((icmp_ln292_fu_1120_p2[0:0] == 1'b1) ? add_ln290_fu_1126_p2 : c_fu_1080_p3);

assign shl_ln291_1_fu_1136_p2 = zext_ln291_1_fu_1132_p1 << c_1_fu_1098_p3;

assign shl_ln291_fu_1110_p2 = zext_ln291_fu_1106_p1 << c_fu_1080_p3;

assign shl_ln379_fu_366_p2 = ref_4oPi_table_100_q0 << zext_ln379_fu_363_p1;

assign shl_ln504_fu_528_p2 = Mx_bits_3_reg_1357 << zext_ln504_fu_525_p1;

assign shl_ln506_fu_585_p2 = zext_ln506_fu_575_p1 << zext_ln506_1_fu_571_p1;

assign sin_basis_fu_684_p3 = ((do_cos_read_reg_1303_pp0_iter2_reg[0:0] == 1'b1) ? tmp_1_fu_603_p19 : xor_ln242_fu_643_p2);

assign sub_ln506_fu_557_p2 = (8'd0 - Ex_1_fu_543_p2);

assign t1_fu_933_p4 = {{second_order_float_sin_cos_K0_q0[29:1]}};

assign t_2_fu_1290_p4 = {{{results_sign_4_reg_1432_pp0_iter4_reg}, {results_exp_1_fu_1245_p3}}, {results_sig_fu_1282_p3}};

assign t_fu_457_p3 = {{tmp_2_fu_447_p4}, {1'd1}};

integer ap_tvar_int_0;

always @ (out_bits_2_fu_1062_p3) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            tmp_10_fu_1088_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_10_fu_1088_p4[ap_tvar_int_0] = out_bits_2_fu_1062_p3[31 - ap_tvar_int_0];
        end
    end
end

assign tmp_11_fu_713_p33 = 'bx;

assign tmp_12_fu_785_p33 = 'bx;

assign tmp_13_fu_1186_p4 = {{shl_ln291_1_fu_1136_p2[27:5]}};

assign tmp_14_fu_1196_p4 = {{shl_ln291_fu_1110_p2[27:5]}};

assign tmp_15_fu_1166_p3 = newexp_fu_1160_p2[32'd31];

assign tmp_1_fu_603_p17 = 'bx;

assign tmp_2_fu_447_p4 = {{Mx_bits_3_fu_439_p3[57:29]}};

assign tmp_3_fu_664_p4 = {{select_ln506_1_fu_591_p3[28:22]}};

assign tmp_4_fu_1034_p4 = {{mul_ln32_fu_290_p2[57:42]}};

integer ap_tvar_int_1;

always @ (out_bits_fu_1044_p3) begin
    for (ap_tvar_int_1 = 32 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 31 - 0) begin
            tmp_5_fu_1070_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_5_fu_1070_p4[ap_tvar_int_1] = out_bits_fu_1044_p3[31 - ap_tvar_int_1];
        end
    end
end

assign tmp_6_fu_549_p3 = Ex_1_fu_543_p2[32'd7];

assign tmp_7_fu_1052_p4 = {{mul_ln32_fu_290_p2[41:29]}};

integer ap_tvar_int_2;

always @ (t_fu_457_p3) begin
    for (ap_tvar_int_2 = 30 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 29 - 0) begin
            tmp_8_fu_465_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            tmp_8_fu_465_p4[ap_tvar_int_2] = t_fu_457_p3[29 - ap_tvar_int_2];
        end
    end
end

assign tmp_9_fu_475_p3 = {{1'd1}, {tmp_8_fu_465_p4}};

assign tmp_fu_414_p3 = h_fu_294_p2[32'd77];


always @ (sext_ln75_fu_483_p1) begin
    if (sext_ln75_fu_483_p1[0] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd0;
    end else if (sext_ln75_fu_483_p1[1] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd1;
    end else if (sext_ln75_fu_483_p1[2] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd2;
    end else if (sext_ln75_fu_483_p1[3] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd3;
    end else if (sext_ln75_fu_483_p1[4] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd4;
    end else if (sext_ln75_fu_483_p1[5] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd5;
    end else if (sext_ln75_fu_483_p1[6] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd6;
    end else if (sext_ln75_fu_483_p1[7] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd7;
    end else if (sext_ln75_fu_483_p1[8] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd8;
    end else if (sext_ln75_fu_483_p1[9] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd9;
    end else if (sext_ln75_fu_483_p1[10] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd10;
    end else if (sext_ln75_fu_483_p1[11] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd11;
    end else if (sext_ln75_fu_483_p1[12] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd12;
    end else if (sext_ln75_fu_483_p1[13] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd13;
    end else if (sext_ln75_fu_483_p1[14] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd14;
    end else if (sext_ln75_fu_483_p1[15] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd15;
    end else if (sext_ln75_fu_483_p1[16] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd16;
    end else if (sext_ln75_fu_483_p1[17] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd17;
    end else if (sext_ln75_fu_483_p1[18] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd18;
    end else if (sext_ln75_fu_483_p1[19] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd19;
    end else if (sext_ln75_fu_483_p1[20] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd20;
    end else if (sext_ln75_fu_483_p1[21] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd21;
    end else if (sext_ln75_fu_483_p1[22] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd22;
    end else if (sext_ln75_fu_483_p1[23] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd23;
    end else if (sext_ln75_fu_483_p1[24] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd24;
    end else if (sext_ln75_fu_483_p1[25] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd25;
    end else if (sext_ln75_fu_483_p1[26] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd26;
    end else if (sext_ln75_fu_483_p1[27] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd27;
    end else if (sext_ln75_fu_483_p1[28] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd28;
    end else if (sext_ln75_fu_483_p1[29] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd29;
    end else if (sext_ln75_fu_483_p1[30] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd30;
    end else if (sext_ln75_fu_483_p1[31] == 1'b1) begin
        tmp_s_fu_487_p3 = 32'd31;
    end else begin
        tmp_s_fu_487_p3 = 32'd32;
    end
end

assign trunc_ln1_fu_972_p4 = {{mul_ln30_fu_966_p2[29:16]}};

assign trunc_ln379_fu_359_p1 = addr_fu_336_p3[3:0];

assign trunc_ln_fu_952_p4 = {{mul_ln29_fu_286_p2[44:23]}};

assign xor_ln242_fu_643_p2 = (tmp_1_fu_603_p19 ^ 1'd1);

assign xor_ln271_fu_1256_p2 = (1'd1 ^ and_ln271_1_fu_1252_p2);

assign xor_ln278_fu_875_p2 = (do_cos_read_reg_1303_pp0_iter2_reg ^ 1'd1);

assign xor_ln282_fu_890_p2 = (icmp_ln282_fu_885_p2 ^ 1'd1);

assign xor_ln451_fu_422_p2 = (closepath_reg_1330_pp0_iter1_reg ^ 1'd1);

assign zext_ln23_fu_910_p1 = B_trunc_reg_1394;

assign zext_ln28_fu_699_p1 = A_fu_691_p3;

assign zext_ln291_1_fu_1132_p1 = in_shift_1_fu_1116_p1;

assign zext_ln291_fu_1106_p1 = result_fu_1020_p4;

assign zext_ln378_fu_354_p1 = lshr_ln_fu_344_p4;

assign zext_ln379_fu_363_p1 = trunc_ln379_reg_1342;

assign zext_ln504_fu_525_p1 = Mx_zeros_reg_1362;

assign zext_ln505_fu_522_p1 = Mx_zeros_reg_1362;

assign zext_ln506_1_fu_571_p1 = select_ln506_fu_563_p3;

assign zext_ln506_fu_575_p1 = Mx_fu_533_p4;

endmodule //hestonEuro_sin_or_cos_float_s
