-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hestonEuro_simulation is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    this_data_timeT_val1 : IN STD_LOGIC_VECTOR (31 downto 0);
    this_data_freeRate_val2 : IN STD_LOGIC_VECTOR (31 downto 0);
    this_data_initPrice_val3 : IN STD_LOGIC_VECTOR (31 downto 0);
    this_data_strikePrice_val4 : IN STD_LOGIC_VECTOR (31 downto 0);
    this_vol_expect_val5 : IN STD_LOGIC_VECTOR (31 downto 0);
    this_vol_kappa_val6 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    this_vol_initValue_val7 : IN STD_LOGIC_VECTOR (31 downto 0);
    this_vol_correlation_val8 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of hestonEuro_simulation is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_6C078965 : STD_LOGIC_VECTOR (31 downto 0) := "01101100000001111000100101100101";
    constant ap_const_lv9_138 : STD_LOGIC_VECTOR (8 downto 0) := "100111000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal shl_ln_fu_405_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln_reg_742 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal xor_ln72_fu_451_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln72_reg_747 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal xor_ln72_1_fu_499_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln72_1_reg_752 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal xor_ln72_2_fu_547_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln72_2_reg_757 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal xor_ln72_3_fu_595_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln72_3_reg_762 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal mt_rng_mt_e_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mt_rng_mt_e_ce0 : STD_LOGIC;
    signal mt_rng_mt_e_we0 : STD_LOGIC;
    signal mt_rng_mt_e_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_e_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_e_ce1 : STD_LOGIC;
    signal mt_rng_mt_e_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_e_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mt_rng_mt_e_1_ce0 : STD_LOGIC;
    signal mt_rng_mt_e_1_we0 : STD_LOGIC;
    signal mt_rng_mt_e_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_e_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_e_1_ce1 : STD_LOGIC;
    signal mt_rng_mt_e_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_e_2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mt_rng_mt_e_2_ce0 : STD_LOGIC;
    signal mt_rng_mt_e_2_we0 : STD_LOGIC;
    signal mt_rng_mt_e_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_e_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_e_2_ce1 : STD_LOGIC;
    signal mt_rng_mt_e_2_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_e_3_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mt_rng_mt_e_3_ce0 : STD_LOGIC;
    signal mt_rng_mt_e_3_we0 : STD_LOGIC;
    signal mt_rng_mt_e_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_e_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_e_3_ce1 : STD_LOGIC;
    signal mt_rng_mt_e_3_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_o_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mt_rng_mt_o_ce0 : STD_LOGIC;
    signal mt_rng_mt_o_we0 : STD_LOGIC;
    signal mt_rng_mt_o_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_o_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_o_ce1 : STD_LOGIC;
    signal mt_rng_mt_o_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_o_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mt_rng_mt_o_1_ce0 : STD_LOGIC;
    signal mt_rng_mt_o_1_we0 : STD_LOGIC;
    signal mt_rng_mt_o_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_o_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_o_1_ce1 : STD_LOGIC;
    signal mt_rng_mt_o_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_o_2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mt_rng_mt_o_2_ce0 : STD_LOGIC;
    signal mt_rng_mt_o_2_we0 : STD_LOGIC;
    signal mt_rng_mt_o_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_o_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_o_2_ce1 : STD_LOGIC;
    signal mt_rng_mt_o_2_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_o_3_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mt_rng_mt_o_3_ce0 : STD_LOGIC;
    signal mt_rng_mt_o_3_we0 : STD_LOGIC;
    signal mt_rng_mt_o_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_o_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mt_rng_mt_o_3_ce1 : STD_LOGIC;
    signal mt_rng_mt_o_3_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sampleSIM_fu_274_ap_start : STD_LOGIC;
    signal grp_sampleSIM_fu_274_ap_done : STD_LOGIC;
    signal grp_sampleSIM_fu_274_ap_idle : STD_LOGIC;
    signal grp_sampleSIM_fu_274_ap_ready : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_0_we0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_0_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce1 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_1_we0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_1_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce1 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_2_we0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_2_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce1 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_3_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_3_we0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_3_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce1 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_0_we0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_0_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce1 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_1_we0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_1_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce1 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_2_we0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_2_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce1 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_3_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_3_we0 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_3_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce1 : STD_LOGIC;
    signal grp_sampleSIM_fu_274_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sampleSIM_fu_274_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sampleSIM_fu_274_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal zext_ln64_fu_379_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln64_fu_351_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add484_i_fu_72 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln72_1_fu_615_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add48_15_i_fu_76 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln72_2_fu_621_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add48_26_i_fu_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln72_3_fu_627_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add48_37_i_fu_84 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln72_4_fu_633_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_88 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln64_fu_357_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln70_fu_430_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln70_1_fu_478_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln70_2_fu_526_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln70_3_fu_574_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_303_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln70_fu_423_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_308_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln70_1_fu_471_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_313_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln70_2_fu_519_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_318_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln70_3_fu_567_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln_fu_391_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln70_fu_413_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln70_1_fu_401_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_303_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln70_fu_419_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln1_fu_437_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln72_1_fu_447_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln70_1_fu_457_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln70_2_fu_467_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_308_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln72_1_fu_485_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln72_2_fu_495_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln70_2_fu_505_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln70_3_fu_515_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_313_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln72_2_fu_533_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln72_3_fu_543_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln70_3_fu_553_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln70_4_fu_563_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_318_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln72_3_fu_581_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln72_4_fu_591_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln72_fu_606_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln72_fu_611_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hestonEuro_sampleSIM IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        this_data_timeT_val : IN STD_LOGIC_VECTOR (31 downto 0);
        this_data_freeRate_val : IN STD_LOGIC_VECTOR (31 downto 0);
        this_data_initPrice_val : IN STD_LOGIC_VECTOR (31 downto 0);
        this_data_strikePrice_val : IN STD_LOGIC_VECTOR (31 downto 0);
        this_vol_expect_val : IN STD_LOGIC_VECTOR (31 downto 0);
        this_vol_kappa_val : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read : IN STD_LOGIC_VECTOR (31 downto 0);
        this_vol_initValue_val : IN STD_LOGIC_VECTOR (31 downto 0);
        this_vol_correlation_val : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_e_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_e_0_ce0 : OUT STD_LOGIC;
        mt_rng_mt_e_0_we0 : OUT STD_LOGIC;
        mt_rng_mt_e_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_e_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_e_0_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_e_0_ce1 : OUT STD_LOGIC;
        mt_rng_mt_e_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_e_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_e_1_ce0 : OUT STD_LOGIC;
        mt_rng_mt_e_1_we0 : OUT STD_LOGIC;
        mt_rng_mt_e_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_e_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_e_1_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_e_1_ce1 : OUT STD_LOGIC;
        mt_rng_mt_e_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_e_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_e_2_ce0 : OUT STD_LOGIC;
        mt_rng_mt_e_2_we0 : OUT STD_LOGIC;
        mt_rng_mt_e_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_e_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_e_2_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_e_2_ce1 : OUT STD_LOGIC;
        mt_rng_mt_e_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_e_3_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_e_3_ce0 : OUT STD_LOGIC;
        mt_rng_mt_e_3_we0 : OUT STD_LOGIC;
        mt_rng_mt_e_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_e_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_e_3_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_e_3_ce1 : OUT STD_LOGIC;
        mt_rng_mt_e_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_o_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_o_0_ce0 : OUT STD_LOGIC;
        mt_rng_mt_o_0_we0 : OUT STD_LOGIC;
        mt_rng_mt_o_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_o_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_o_0_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_o_0_ce1 : OUT STD_LOGIC;
        mt_rng_mt_o_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_o_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_o_1_ce0 : OUT STD_LOGIC;
        mt_rng_mt_o_1_we0 : OUT STD_LOGIC;
        mt_rng_mt_o_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_o_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_o_1_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_o_1_ce1 : OUT STD_LOGIC;
        mt_rng_mt_o_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_o_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_o_2_ce0 : OUT STD_LOGIC;
        mt_rng_mt_o_2_we0 : OUT STD_LOGIC;
        mt_rng_mt_o_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_o_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_o_2_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_o_2_ce1 : OUT STD_LOGIC;
        mt_rng_mt_o_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_o_3_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_o_3_ce0 : OUT STD_LOGIC;
        mt_rng_mt_o_3_we0 : OUT STD_LOGIC;
        mt_rng_mt_o_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_o_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mt_rng_mt_o_3_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        mt_rng_mt_o_3_ce1 : OUT STD_LOGIC;
        mt_rng_mt_o_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component hestonEuro_mul_32s_32ns_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    mt_rng_mt_e_U : component hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 312,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => mt_rng_mt_e_address0,
        ce0 => mt_rng_mt_e_ce0,
        we0 => mt_rng_mt_e_we0,
        d0 => mt_rng_mt_e_d0,
        q0 => mt_rng_mt_e_q0,
        address1 => grp_sampleSIM_fu_274_mt_rng_mt_e_0_address1,
        ce1 => mt_rng_mt_e_ce1,
        q1 => mt_rng_mt_e_q1);

    mt_rng_mt_e_1_U : component hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 312,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => mt_rng_mt_e_1_address0,
        ce0 => mt_rng_mt_e_1_ce0,
        we0 => mt_rng_mt_e_1_we0,
        d0 => mt_rng_mt_e_1_d0,
        q0 => mt_rng_mt_e_1_q0,
        address1 => grp_sampleSIM_fu_274_mt_rng_mt_e_1_address1,
        ce1 => mt_rng_mt_e_1_ce1,
        q1 => mt_rng_mt_e_1_q1);

    mt_rng_mt_e_2_U : component hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 312,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => mt_rng_mt_e_2_address0,
        ce0 => mt_rng_mt_e_2_ce0,
        we0 => mt_rng_mt_e_2_we0,
        d0 => mt_rng_mt_e_2_d0,
        q0 => mt_rng_mt_e_2_q0,
        address1 => grp_sampleSIM_fu_274_mt_rng_mt_e_2_address1,
        ce1 => mt_rng_mt_e_2_ce1,
        q1 => mt_rng_mt_e_2_q1);

    mt_rng_mt_e_3_U : component hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 312,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => mt_rng_mt_e_3_address0,
        ce0 => mt_rng_mt_e_3_ce0,
        we0 => mt_rng_mt_e_3_we0,
        d0 => mt_rng_mt_e_3_d0,
        q0 => mt_rng_mt_e_3_q0,
        address1 => grp_sampleSIM_fu_274_mt_rng_mt_e_3_address1,
        ce1 => mt_rng_mt_e_3_ce1,
        q1 => mt_rng_mt_e_3_q1);

    mt_rng_mt_o_U : component hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 312,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => mt_rng_mt_o_address0,
        ce0 => mt_rng_mt_o_ce0,
        we0 => mt_rng_mt_o_we0,
        d0 => mt_rng_mt_o_d0,
        q0 => mt_rng_mt_o_q0,
        address1 => grp_sampleSIM_fu_274_mt_rng_mt_o_0_address1,
        ce1 => mt_rng_mt_o_ce1,
        q1 => mt_rng_mt_o_q1);

    mt_rng_mt_o_1_U : component hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 312,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => mt_rng_mt_o_1_address0,
        ce0 => mt_rng_mt_o_1_ce0,
        we0 => mt_rng_mt_o_1_we0,
        d0 => mt_rng_mt_o_1_d0,
        q0 => mt_rng_mt_o_1_q0,
        address1 => grp_sampleSIM_fu_274_mt_rng_mt_o_1_address1,
        ce1 => mt_rng_mt_o_1_ce1,
        q1 => mt_rng_mt_o_1_q1);

    mt_rng_mt_o_2_U : component hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 312,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => mt_rng_mt_o_2_address0,
        ce0 => mt_rng_mt_o_2_ce0,
        we0 => mt_rng_mt_o_2_we0,
        d0 => mt_rng_mt_o_2_d0,
        q0 => mt_rng_mt_o_2_q0,
        address1 => grp_sampleSIM_fu_274_mt_rng_mt_o_2_address1,
        ce1 => mt_rng_mt_o_2_ce1,
        q1 => mt_rng_mt_o_2_q1);

    mt_rng_mt_o_3_U : component hestonEuro_simulation_mt_rng_mt_e_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 312,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => mt_rng_mt_o_3_address0,
        ce0 => mt_rng_mt_o_3_ce0,
        we0 => mt_rng_mt_o_3_we0,
        d0 => mt_rng_mt_o_3_d0,
        q0 => mt_rng_mt_o_3_q0,
        address1 => grp_sampleSIM_fu_274_mt_rng_mt_o_3_address1,
        ce1 => mt_rng_mt_o_3_ce1,
        q1 => mt_rng_mt_o_3_q1);

    grp_sampleSIM_fu_274 : component hestonEuro_sampleSIM
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sampleSIM_fu_274_ap_start,
        ap_done => grp_sampleSIM_fu_274_ap_done,
        ap_idle => grp_sampleSIM_fu_274_ap_idle,
        ap_ready => grp_sampleSIM_fu_274_ap_ready,
        this_data_timeT_val => this_data_timeT_val1,
        this_data_freeRate_val => this_data_freeRate_val2,
        this_data_initPrice_val => this_data_initPrice_val3,
        this_data_strikePrice_val => this_data_strikePrice_val4,
        this_vol_expect_val => this_vol_expect_val5,
        this_vol_kappa_val => this_vol_kappa_val6,
        p_read => p_read,
        this_vol_initValue_val => this_vol_initValue_val7,
        this_vol_correlation_val => this_vol_correlation_val8,
        mt_rng_mt_e_0_address0 => grp_sampleSIM_fu_274_mt_rng_mt_e_0_address0,
        mt_rng_mt_e_0_ce0 => grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce0,
        mt_rng_mt_e_0_we0 => grp_sampleSIM_fu_274_mt_rng_mt_e_0_we0,
        mt_rng_mt_e_0_d0 => grp_sampleSIM_fu_274_mt_rng_mt_e_0_d0,
        mt_rng_mt_e_0_q0 => mt_rng_mt_e_q0,
        mt_rng_mt_e_0_address1 => grp_sampleSIM_fu_274_mt_rng_mt_e_0_address1,
        mt_rng_mt_e_0_ce1 => grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce1,
        mt_rng_mt_e_0_q1 => mt_rng_mt_e_q1,
        mt_rng_mt_e_1_address0 => grp_sampleSIM_fu_274_mt_rng_mt_e_1_address0,
        mt_rng_mt_e_1_ce0 => grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce0,
        mt_rng_mt_e_1_we0 => grp_sampleSIM_fu_274_mt_rng_mt_e_1_we0,
        mt_rng_mt_e_1_d0 => grp_sampleSIM_fu_274_mt_rng_mt_e_1_d0,
        mt_rng_mt_e_1_q0 => mt_rng_mt_e_1_q0,
        mt_rng_mt_e_1_address1 => grp_sampleSIM_fu_274_mt_rng_mt_e_1_address1,
        mt_rng_mt_e_1_ce1 => grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce1,
        mt_rng_mt_e_1_q1 => mt_rng_mt_e_1_q1,
        mt_rng_mt_e_2_address0 => grp_sampleSIM_fu_274_mt_rng_mt_e_2_address0,
        mt_rng_mt_e_2_ce0 => grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce0,
        mt_rng_mt_e_2_we0 => grp_sampleSIM_fu_274_mt_rng_mt_e_2_we0,
        mt_rng_mt_e_2_d0 => grp_sampleSIM_fu_274_mt_rng_mt_e_2_d0,
        mt_rng_mt_e_2_q0 => mt_rng_mt_e_2_q0,
        mt_rng_mt_e_2_address1 => grp_sampleSIM_fu_274_mt_rng_mt_e_2_address1,
        mt_rng_mt_e_2_ce1 => grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce1,
        mt_rng_mt_e_2_q1 => mt_rng_mt_e_2_q1,
        mt_rng_mt_e_3_address0 => grp_sampleSIM_fu_274_mt_rng_mt_e_3_address0,
        mt_rng_mt_e_3_ce0 => grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce0,
        mt_rng_mt_e_3_we0 => grp_sampleSIM_fu_274_mt_rng_mt_e_3_we0,
        mt_rng_mt_e_3_d0 => grp_sampleSIM_fu_274_mt_rng_mt_e_3_d0,
        mt_rng_mt_e_3_q0 => mt_rng_mt_e_3_q0,
        mt_rng_mt_e_3_address1 => grp_sampleSIM_fu_274_mt_rng_mt_e_3_address1,
        mt_rng_mt_e_3_ce1 => grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce1,
        mt_rng_mt_e_3_q1 => mt_rng_mt_e_3_q1,
        mt_rng_mt_o_0_address0 => grp_sampleSIM_fu_274_mt_rng_mt_o_0_address0,
        mt_rng_mt_o_0_ce0 => grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce0,
        mt_rng_mt_o_0_we0 => grp_sampleSIM_fu_274_mt_rng_mt_o_0_we0,
        mt_rng_mt_o_0_d0 => grp_sampleSIM_fu_274_mt_rng_mt_o_0_d0,
        mt_rng_mt_o_0_q0 => mt_rng_mt_o_q0,
        mt_rng_mt_o_0_address1 => grp_sampleSIM_fu_274_mt_rng_mt_o_0_address1,
        mt_rng_mt_o_0_ce1 => grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce1,
        mt_rng_mt_o_0_q1 => mt_rng_mt_o_q1,
        mt_rng_mt_o_1_address0 => grp_sampleSIM_fu_274_mt_rng_mt_o_1_address0,
        mt_rng_mt_o_1_ce0 => grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce0,
        mt_rng_mt_o_1_we0 => grp_sampleSIM_fu_274_mt_rng_mt_o_1_we0,
        mt_rng_mt_o_1_d0 => grp_sampleSIM_fu_274_mt_rng_mt_o_1_d0,
        mt_rng_mt_o_1_q0 => mt_rng_mt_o_1_q0,
        mt_rng_mt_o_1_address1 => grp_sampleSIM_fu_274_mt_rng_mt_o_1_address1,
        mt_rng_mt_o_1_ce1 => grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce1,
        mt_rng_mt_o_1_q1 => mt_rng_mt_o_1_q1,
        mt_rng_mt_o_2_address0 => grp_sampleSIM_fu_274_mt_rng_mt_o_2_address0,
        mt_rng_mt_o_2_ce0 => grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce0,
        mt_rng_mt_o_2_we0 => grp_sampleSIM_fu_274_mt_rng_mt_o_2_we0,
        mt_rng_mt_o_2_d0 => grp_sampleSIM_fu_274_mt_rng_mt_o_2_d0,
        mt_rng_mt_o_2_q0 => mt_rng_mt_o_2_q0,
        mt_rng_mt_o_2_address1 => grp_sampleSIM_fu_274_mt_rng_mt_o_2_address1,
        mt_rng_mt_o_2_ce1 => grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce1,
        mt_rng_mt_o_2_q1 => mt_rng_mt_o_2_q1,
        mt_rng_mt_o_3_address0 => grp_sampleSIM_fu_274_mt_rng_mt_o_3_address0,
        mt_rng_mt_o_3_ce0 => grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce0,
        mt_rng_mt_o_3_we0 => grp_sampleSIM_fu_274_mt_rng_mt_o_3_we0,
        mt_rng_mt_o_3_d0 => grp_sampleSIM_fu_274_mt_rng_mt_o_3_d0,
        mt_rng_mt_o_3_q0 => mt_rng_mt_o_3_q0,
        mt_rng_mt_o_3_address1 => grp_sampleSIM_fu_274_mt_rng_mt_o_3_address1,
        mt_rng_mt_o_3_ce1 => grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce1,
        mt_rng_mt_o_3_q1 => mt_rng_mt_o_3_q1,
        ap_return_0 => grp_sampleSIM_fu_274_ap_return_0,
        ap_return_1 => grp_sampleSIM_fu_274_ap_return_1);

    mul_32s_32ns_32_1_1_U261 : component hestonEuro_mul_32s_32ns_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_303_p0,
        din1 => ap_const_lv32_6C078965,
        dout => grp_fu_303_p2);

    mul_32s_32ns_32_1_1_U262 : component hestonEuro_mul_32s_32ns_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_308_p0,
        din1 => ap_const_lv32_6C078965,
        dout => grp_fu_308_p2);

    mul_32s_32ns_32_1_1_U263 : component hestonEuro_mul_32s_32ns_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_313_p0,
        din1 => ap_const_lv32_6C078965,
        dout => grp_fu_313_p2);

    mul_32s_32ns_32_1_1_U264 : component hestonEuro_mul_32s_32ns_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_318_p0,
        din1 => ap_const_lv32_6C078965,
        dout => grp_fu_318_p2);





    add484_i_fu_72_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                add484_i_fu_72 <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    add484_i_fu_72 <= ap_const_lv32_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    add484_i_fu_72 <= add_ln72_1_fu_615_p2;
                end if; 
            end if;
        end if;
    end process;


    add48_15_i_fu_76_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                add48_15_i_fu_76 <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    add48_15_i_fu_76 <= ap_const_lv32_1;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    add48_15_i_fu_76 <= add_ln72_2_fu_621_p2;
                end if; 
            end if;
        end if;
    end process;


    add48_26_i_fu_80_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                add48_26_i_fu_80 <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    add48_26_i_fu_80 <= ap_const_lv32_2;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    add48_26_i_fu_80 <= add_ln72_3_fu_627_p2;
                end if; 
            end if;
        end if;
    end process;


    add48_37_i_fu_84_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                add48_37_i_fu_84 <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    add48_37_i_fu_84 <= ap_const_lv32_3;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    add48_37_i_fu_84 <= add_ln72_4_fu_633_p2;
                end if; 
            end if;
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv32_0;
            else
                if (((grp_sampleSIM_fu_274_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_return_0_preg <= grp_sampleSIM_fu_274_ap_return_0;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv32_0;
            else
                if (((grp_sampleSIM_fu_274_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_return_1_preg <= grp_sampleSIM_fu_274_ap_return_1;
                end if; 
            end if;
        end if;
    end process;


    grp_sampleSIM_fu_274_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sampleSIM_fu_274_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_sampleSIM_fu_274_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sampleSIM_fu_274_ap_ready = ap_const_logic_1)) then 
                    grp_sampleSIM_fu_274_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_88_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                i_fu_88 <= ap_const_lv9_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    i_fu_88 <= ap_const_lv9_0;
                elsif (((icmp_ln64_fu_351_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    i_fu_88 <= add_ln64_fu_357_p2;
                end if; 
            end if;
        end if;
    end process;


    shl_ln_reg_742_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                shl_ln_reg_742(1) <= '0';
                shl_ln_reg_742(2) <= '0';
                shl_ln_reg_742(3) <= '0';
                shl_ln_reg_742(4) <= '0';
                shl_ln_reg_742(5) <= '0';
                shl_ln_reg_742(6) <= '0';
                shl_ln_reg_742(7) <= '0';
                shl_ln_reg_742(8) <= '0';
                shl_ln_reg_742(9) <= '0';
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                                        shl_ln_reg_742(9 downto 1) <= shl_ln_fu_405_p3(9 downto 1);
                end if; 
            end if;
        end if;
    end process;


    xor_ln72_1_reg_752_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                xor_ln72_1_reg_752 <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    xor_ln72_1_reg_752 <= xor_ln72_1_fu_499_p2;
                end if; 
            end if;
        end if;
    end process;


    xor_ln72_2_reg_757_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                xor_ln72_2_reg_757 <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    xor_ln72_2_reg_757 <= xor_ln72_2_fu_547_p2;
                end if; 
            end if;
        end if;
    end process;


    xor_ln72_3_reg_762_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                xor_ln72_3_reg_762 <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    xor_ln72_3_reg_762 <= xor_ln72_3_fu_595_p2;
                end if; 
            end if;
        end if;
    end process;


    xor_ln72_reg_747_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                xor_ln72_reg_747 <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    xor_ln72_reg_747 <= xor_ln72_fu_451_p2;
                end if; 
            end if;
        end if;
    end process;

    shl_ln_reg_742(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_sampleSIM_fu_274_ap_done, ap_CS_fsm_state5, icmp_ln64_fu_351_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln64_fu_351_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_sampleSIM_fu_274_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln64_fu_357_p2 <= std_logic_vector(unsigned(i_fu_88) + unsigned(ap_const_lv9_1));
    add_ln70_1_fu_478_p2 <= std_logic_vector(unsigned(grp_fu_308_p2) + unsigned(zext_ln70_fu_419_p1));
    add_ln70_2_fu_526_p2 <= std_logic_vector(unsigned(grp_fu_313_p2) + unsigned(zext_ln70_fu_419_p1));
    add_ln70_3_fu_574_p2 <= std_logic_vector(unsigned(grp_fu_318_p2) + unsigned(zext_ln70_fu_419_p1));
    add_ln70_fu_430_p2 <= std_logic_vector(unsigned(grp_fu_303_p2) + unsigned(zext_ln70_fu_419_p1));
    add_ln72_1_fu_615_p2 <= std_logic_vector(unsigned(grp_fu_303_p2) + unsigned(zext_ln72_fu_611_p1));
    add_ln72_2_fu_621_p2 <= std_logic_vector(unsigned(grp_fu_308_p2) + unsigned(zext_ln72_fu_611_p1));
    add_ln72_3_fu_627_p2 <= std_logic_vector(unsigned(grp_fu_313_p2) + unsigned(zext_ln72_fu_611_p1));
    add_ln72_4_fu_633_p2 <= std_logic_vector(unsigned(grp_fu_318_p2) + unsigned(zext_ln72_fu_611_p1));
    add_ln72_fu_606_p2 <= std_logic_vector(unsigned(shl_ln_reg_742) + unsigned(ap_const_lv10_2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_sampleSIM_fu_274_ap_done)
    begin
        if ((grp_sampleSIM_fu_274_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_sampleSIM_fu_274_ap_done, ap_CS_fsm_state5)
    begin
        if ((((grp_sampleSIM_fu_274_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_sampleSIM_fu_274_ap_done, ap_CS_fsm_state5)
    begin
        if (((grp_sampleSIM_fu_274_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(grp_sampleSIM_fu_274_ap_done, grp_sampleSIM_fu_274_ap_return_0, ap_CS_fsm_state5, ap_return_0_preg)
    begin
        if (((grp_sampleSIM_fu_274_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_return_0 <= grp_sampleSIM_fu_274_ap_return_0;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(grp_sampleSIM_fu_274_ap_done, grp_sampleSIM_fu_274_ap_return_1, ap_CS_fsm_state5, ap_return_1_preg)
    begin
        if (((grp_sampleSIM_fu_274_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_return_1 <= grp_sampleSIM_fu_274_ap_return_1;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    grp_fu_303_p0_assign_proc : process(ap_CS_fsm_state2, xor_ln72_reg_747, ap_CS_fsm_state3, xor_ln70_fu_423_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_303_p0 <= xor_ln72_reg_747;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_303_p0 <= xor_ln70_fu_423_p2;
        else 
            grp_fu_303_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_308_p0_assign_proc : process(ap_CS_fsm_state2, xor_ln72_1_reg_752, ap_CS_fsm_state3, xor_ln70_1_fu_471_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_308_p0 <= xor_ln72_1_reg_752;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_308_p0 <= xor_ln70_1_fu_471_p2;
        else 
            grp_fu_308_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_313_p0_assign_proc : process(ap_CS_fsm_state2, xor_ln72_2_reg_757, ap_CS_fsm_state3, xor_ln70_2_fu_519_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_313_p0 <= xor_ln72_2_reg_757;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_313_p0 <= xor_ln70_2_fu_519_p2;
        else 
            grp_fu_313_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_318_p0_assign_proc : process(ap_CS_fsm_state2, xor_ln72_3_reg_762, ap_CS_fsm_state3, xor_ln70_3_fu_567_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_318_p0 <= xor_ln72_3_reg_762;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_318_p0 <= xor_ln70_3_fu_567_p2;
        else 
            grp_fu_318_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_sampleSIM_fu_274_ap_start <= grp_sampleSIM_fu_274_ap_start_reg;
    icmp_ln64_fu_351_p2 <= "1" when (i_fu_88 = ap_const_lv9_138) else "0";
    lshr_ln1_fu_437_p4 <= add_ln70_fu_430_p2(31 downto 30);
    lshr_ln70_1_fu_457_p4 <= add48_15_i_fu_76(31 downto 30);
    lshr_ln70_2_fu_505_p4 <= add48_26_i_fu_80(31 downto 30);
    lshr_ln70_3_fu_553_p4 <= add48_37_i_fu_84(31 downto 30);
    lshr_ln72_1_fu_485_p4 <= add_ln70_1_fu_478_p2(31 downto 30);
    lshr_ln72_2_fu_533_p4 <= add_ln70_2_fu_526_p2(31 downto 30);
    lshr_ln72_3_fu_581_p4 <= add_ln70_3_fu_574_p2(31 downto 30);
    lshr_ln_fu_391_p4 <= add484_i_fu_72(31 downto 30);

    mt_rng_mt_e_1_address0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_1_address0, ap_CS_fsm_state5, zext_ln64_fu_379_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_e_1_address0 <= zext_ln64_fu_379_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_1_address0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_1_address0;
        else 
            mt_rng_mt_e_1_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_e_1_ce0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_e_1_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_1_ce0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce0;
        else 
            mt_rng_mt_e_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_e_1_ce1_assign_proc : process(grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_1_ce1 <= grp_sampleSIM_fu_274_mt_rng_mt_e_1_ce1;
        else 
            mt_rng_mt_e_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_e_1_d0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_1_d0, ap_CS_fsm_state5, add48_15_i_fu_76)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_e_1_d0 <= add48_15_i_fu_76;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_1_d0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_1_d0;
        else 
            mt_rng_mt_e_1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_e_1_we0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_1_we0, ap_CS_fsm_state5, icmp_ln64_fu_351_p2)
    begin
        if (((icmp_ln64_fu_351_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            mt_rng_mt_e_1_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_1_we0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_1_we0;
        else 
            mt_rng_mt_e_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_e_2_address0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_2_address0, ap_CS_fsm_state5, zext_ln64_fu_379_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_e_2_address0 <= zext_ln64_fu_379_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_2_address0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_2_address0;
        else 
            mt_rng_mt_e_2_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_e_2_ce0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_e_2_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_2_ce0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce0;
        else 
            mt_rng_mt_e_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_e_2_ce1_assign_proc : process(grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_2_ce1 <= grp_sampleSIM_fu_274_mt_rng_mt_e_2_ce1;
        else 
            mt_rng_mt_e_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_e_2_d0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_2_d0, ap_CS_fsm_state5, add48_26_i_fu_80)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_e_2_d0 <= add48_26_i_fu_80;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_2_d0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_2_d0;
        else 
            mt_rng_mt_e_2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_e_2_we0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_2_we0, ap_CS_fsm_state5, icmp_ln64_fu_351_p2)
    begin
        if (((icmp_ln64_fu_351_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            mt_rng_mt_e_2_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_2_we0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_2_we0;
        else 
            mt_rng_mt_e_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_e_3_address0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_3_address0, ap_CS_fsm_state5, zext_ln64_fu_379_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_e_3_address0 <= zext_ln64_fu_379_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_3_address0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_3_address0;
        else 
            mt_rng_mt_e_3_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_e_3_ce0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_e_3_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_3_ce0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce0;
        else 
            mt_rng_mt_e_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_e_3_ce1_assign_proc : process(grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_3_ce1 <= grp_sampleSIM_fu_274_mt_rng_mt_e_3_ce1;
        else 
            mt_rng_mt_e_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_e_3_d0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_3_d0, ap_CS_fsm_state5, add48_37_i_fu_84)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_e_3_d0 <= add48_37_i_fu_84;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_3_d0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_3_d0;
        else 
            mt_rng_mt_e_3_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_e_3_we0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_3_we0, ap_CS_fsm_state5, icmp_ln64_fu_351_p2)
    begin
        if (((icmp_ln64_fu_351_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            mt_rng_mt_e_3_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_3_we0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_3_we0;
        else 
            mt_rng_mt_e_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_e_address0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_0_address0, ap_CS_fsm_state5, zext_ln64_fu_379_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_e_address0 <= zext_ln64_fu_379_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_address0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_0_address0;
        else 
            mt_rng_mt_e_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_e_ce0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_e_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_ce0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce0;
        else 
            mt_rng_mt_e_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_e_ce1_assign_proc : process(grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_ce1 <= grp_sampleSIM_fu_274_mt_rng_mt_e_0_ce1;
        else 
            mt_rng_mt_e_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_e_d0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_0_d0, ap_CS_fsm_state5, add484_i_fu_72)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_e_d0 <= add484_i_fu_72;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_d0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_0_d0;
        else 
            mt_rng_mt_e_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_e_we0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_e_0_we0, ap_CS_fsm_state5, icmp_ln64_fu_351_p2)
    begin
        if (((icmp_ln64_fu_351_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            mt_rng_mt_e_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_e_we0 <= grp_sampleSIM_fu_274_mt_rng_mt_e_0_we0;
        else 
            mt_rng_mt_e_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_o_1_address0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_1_address0, ap_CS_fsm_state5, zext_ln64_fu_379_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_o_1_address0 <= zext_ln64_fu_379_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_1_address0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_1_address0;
        else 
            mt_rng_mt_o_1_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_o_1_ce0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_o_1_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_1_ce0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce0;
        else 
            mt_rng_mt_o_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_o_1_ce1_assign_proc : process(grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_1_ce1 <= grp_sampleSIM_fu_274_mt_rng_mt_o_1_ce1;
        else 
            mt_rng_mt_o_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_o_1_d0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_1_d0, ap_CS_fsm_state5, add_ln70_1_fu_478_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_o_1_d0 <= add_ln70_1_fu_478_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_1_d0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_1_d0;
        else 
            mt_rng_mt_o_1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_o_1_we0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_1_we0, ap_CS_fsm_state5, icmp_ln64_fu_351_p2)
    begin
        if (((icmp_ln64_fu_351_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            mt_rng_mt_o_1_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_1_we0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_1_we0;
        else 
            mt_rng_mt_o_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_o_2_address0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_2_address0, ap_CS_fsm_state5, zext_ln64_fu_379_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_o_2_address0 <= zext_ln64_fu_379_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_2_address0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_2_address0;
        else 
            mt_rng_mt_o_2_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_o_2_ce0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_o_2_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_2_ce0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce0;
        else 
            mt_rng_mt_o_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_o_2_ce1_assign_proc : process(grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_2_ce1 <= grp_sampleSIM_fu_274_mt_rng_mt_o_2_ce1;
        else 
            mt_rng_mt_o_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_o_2_d0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_2_d0, ap_CS_fsm_state5, add_ln70_2_fu_526_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_o_2_d0 <= add_ln70_2_fu_526_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_2_d0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_2_d0;
        else 
            mt_rng_mt_o_2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_o_2_we0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_2_we0, ap_CS_fsm_state5, icmp_ln64_fu_351_p2)
    begin
        if (((icmp_ln64_fu_351_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            mt_rng_mt_o_2_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_2_we0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_2_we0;
        else 
            mt_rng_mt_o_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_o_3_address0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_3_address0, ap_CS_fsm_state5, zext_ln64_fu_379_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_o_3_address0 <= zext_ln64_fu_379_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_3_address0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_3_address0;
        else 
            mt_rng_mt_o_3_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_o_3_ce0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_o_3_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_3_ce0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce0;
        else 
            mt_rng_mt_o_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_o_3_ce1_assign_proc : process(grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_3_ce1 <= grp_sampleSIM_fu_274_mt_rng_mt_o_3_ce1;
        else 
            mt_rng_mt_o_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_o_3_d0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_3_d0, ap_CS_fsm_state5, add_ln70_3_fu_574_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_o_3_d0 <= add_ln70_3_fu_574_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_3_d0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_3_d0;
        else 
            mt_rng_mt_o_3_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_o_3_we0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_3_we0, ap_CS_fsm_state5, icmp_ln64_fu_351_p2)
    begin
        if (((icmp_ln64_fu_351_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            mt_rng_mt_o_3_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_3_we0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_3_we0;
        else 
            mt_rng_mt_o_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_o_address0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_0_address0, ap_CS_fsm_state5, zext_ln64_fu_379_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_o_address0 <= zext_ln64_fu_379_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_address0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_0_address0;
        else 
            mt_rng_mt_o_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_o_ce0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_o_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_ce0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce0;
        else 
            mt_rng_mt_o_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_o_ce1_assign_proc : process(grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_ce1 <= grp_sampleSIM_fu_274_mt_rng_mt_o_0_ce1;
        else 
            mt_rng_mt_o_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mt_rng_mt_o_d0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_0_d0, ap_CS_fsm_state5, add_ln70_fu_430_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mt_rng_mt_o_d0 <= add_ln70_fu_430_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_d0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_0_d0;
        else 
            mt_rng_mt_o_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mt_rng_mt_o_we0_assign_proc : process(ap_CS_fsm_state2, grp_sampleSIM_fu_274_mt_rng_mt_o_0_we0, ap_CS_fsm_state5, icmp_ln64_fu_351_p2)
    begin
        if (((icmp_ln64_fu_351_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            mt_rng_mt_o_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mt_rng_mt_o_we0 <= grp_sampleSIM_fu_274_mt_rng_mt_o_0_we0;
        else 
            mt_rng_mt_o_we0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln70_fu_413_p2 <= (shl_ln_fu_405_p3 or ap_const_lv10_1);
    shl_ln_fu_405_p3 <= (i_fu_88 & ap_const_lv1_0);
    xor_ln70_1_fu_471_p2 <= (zext_ln70_2_fu_467_p1 xor add48_15_i_fu_76);
    xor_ln70_2_fu_519_p2 <= (zext_ln70_3_fu_515_p1 xor add48_26_i_fu_80);
    xor_ln70_3_fu_567_p2 <= (zext_ln70_4_fu_563_p1 xor add48_37_i_fu_84);
    xor_ln70_fu_423_p2 <= (zext_ln70_1_fu_401_p1 xor add484_i_fu_72);
    xor_ln72_1_fu_499_p2 <= (zext_ln72_2_fu_495_p1 xor add_ln70_1_fu_478_p2);
    xor_ln72_2_fu_547_p2 <= (zext_ln72_3_fu_543_p1 xor add_ln70_2_fu_526_p2);
    xor_ln72_3_fu_595_p2 <= (zext_ln72_4_fu_591_p1 xor add_ln70_3_fu_574_p2);
    xor_ln72_fu_451_p2 <= (zext_ln72_1_fu_447_p1 xor add_ln70_fu_430_p2);
    zext_ln64_fu_379_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_88),64));
    zext_ln70_1_fu_401_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_391_p4),32));
    zext_ln70_2_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln70_1_fu_457_p4),32));
    zext_ln70_3_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln70_2_fu_505_p4),32));
    zext_ln70_4_fu_563_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln70_3_fu_553_p4),32));
    zext_ln70_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln70_fu_413_p2),32));
    zext_ln72_1_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_437_p4),32));
    zext_ln72_2_fu_495_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln72_1_fu_485_p4),32));
    zext_ln72_3_fu_543_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln72_2_fu_533_p4),32));
    zext_ln72_4_fu_591_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln72_3_fu_581_p4),32));
    zext_ln72_fu_611_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_fu_606_p2),32));
end behav;
