-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hestonEuro_sin_or_cos_float_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    t_in : IN STD_LOGIC_VECTOR (31 downto 0);
    do_cos : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of hestonEuro_sin_or_cos_float_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv8_C2 : STD_LOGIC_VECTOR (7 downto 0) := "11000010";
    constant ap_const_lv8_3F : STD_LOGIC_VECTOR (7 downto 0) := "00111111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_4C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001100";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv58_0 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv8_83 : STD_LOGIC_VECTOR (7 downto 0) := "10000011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv29_1FFFFFFF : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111111111111111111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv19_40000 : STD_LOGIC_VECTOR (18 downto 0) := "1000000000000000000";
    constant ap_const_lv9_7F : STD_LOGIC_VECTOR (8 downto 0) := "001111111";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv23_7FFFFF : STD_LOGIC_VECTOR (22 downto 0) := "11111111111111111111111";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv80_0 : STD_LOGIC_VECTOR (79 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ref_4oPi_table_100_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ref_4oPi_table_100_ce0 : STD_LOGIC;
    signal ref_4oPi_table_100_q0 : STD_LOGIC_VECTOR (99 downto 0);
    signal second_order_float_sin_cos_K0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal second_order_float_sin_cos_K0_ce0 : STD_LOGIC;
    signal second_order_float_sin_cos_K0_q0 : STD_LOGIC_VECTOR (29 downto 0);
    signal second_order_float_sin_cos_K1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal second_order_float_sin_cos_K1_ce0 : STD_LOGIC;
    signal second_order_float_sin_cos_K1_q0 : STD_LOGIC_VECTOR (22 downto 0);
    signal second_order_float_sin_cos_K2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal second_order_float_sin_cos_K2_ce0 : STD_LOGIC;
    signal second_order_float_sin_cos_K2_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal do_cos_read_reg_1303 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal do_cos_read_reg_1303_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal do_cos_read_reg_1303_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal do_cos_read_reg_1303_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal do_cos_read_reg_1303_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal din_sign_reg_1311 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal din_sign_reg_1311_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal din_sign_reg_1311_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal din_exp_fu_310_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal din_exp_reg_1317 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal din_exp_reg_1317_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal din_exp_reg_1317_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal din_sig_fu_320_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal din_sig_reg_1324 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    signal din_sig_reg_1324_pp0_iter1_reg : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    signal closepath_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1330 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal closepath_reg_1330_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal closepath_reg_1330_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal trunc_ln379_fu_359_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln379_reg_1342 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal Med_reg_1347 : STD_LOGIC_VECTOR (79 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal k_reg_1352 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal Mx_bits_3_fu_439_p3 : STD_LOGIC_VECTOR (57 downto 0);
    signal Mx_bits_3_reg_1357 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000000";
    signal Mx_zeros_fu_495_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal Mx_zeros_reg_1362 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal icmp_ln271_1_fu_499_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln271_1_reg_1368 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal icmp_ln271_1_reg_1368_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal icmp_ln271_1_reg_1368_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal Ex_1_fu_543_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_1_reg_1374 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal Ex_1_reg_1374_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal B_fu_599_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal B_reg_1379 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    signal cos_basis_fu_649_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal cos_basis_reg_1384 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal cos_basis_reg_1384_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal Mx_1_fu_656_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal Mx_1_reg_1389 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    signal Mx_1_reg_1389_pp0_iter4_reg : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    signal B_trunc_reg_1394 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal icmp_ln271_fu_865_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln271_reg_1414 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal icmp_ln271_reg_1414_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal and_ln271_fu_870_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1419 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal and_ln271_reg_1419_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal icmp_ln282_fu_885_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1425 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal icmp_ln282_reg_1425_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal results_sign_4_fu_902_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_4_reg_1432 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal results_sign_4_reg_1432_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal add_ln32_1_fu_1000_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln32_1_reg_1437 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    signal zext_ln378_fu_354_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln28_fu_699_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln29_fu_286_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal mul_ln32_fu_290_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal h_fu_294_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal data_fu_298_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln376_fu_330_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal addr_fu_336_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln_fu_344_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln379_fu_363_p1 : STD_LOGIC_VECTOR (99 downto 0);
    signal shl_ln379_fu_366_p2 : STD_LOGIC_VECTOR (99 downto 0);
    signal X_fu_382_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal h_fu_294_p2 : STD_LOGIC_VECTOR (79 downto 0);
    signal tmp_fu_414_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln451_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Mx_bits_fu_394_p4 : STD_LOGIC_VECTOR (57 downto 0);
    signal and_ln451_fu_427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Mx_bits_1_fu_433_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal tmp_2_fu_447_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal t_fu_457_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_8_fu_465_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_9_fu_475_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln75_fu_483_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_487_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal Ex_fu_504_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln504_fu_525_p1 : STD_LOGIC_VECTOR (57 downto 0);
    signal shl_ln504_fu_528_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal select_ln453_fu_509_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln505_fu_522_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_549_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln506_fu_557_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln506_fu_563_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal Mx_fu_533_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln506_fu_575_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln506_1_fu_571_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln506_fu_579_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln506_fu_585_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln506_1_fu_591_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_603_p17 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_1_fu_516_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_603_p19 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln242_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sin_basis_fu_684_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_664_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal A_fu_691_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_fu_713_p33 : STD_LOGIC_VECTOR (0 downto 0);
    signal index_fu_706_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p33 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_713_p35 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_785_p35 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln278_fu_875_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_fu_857_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln282_fu_890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_2_fu_880_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_fu_896_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln23_fu_913_p0 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln23_fu_910_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln23_fu_913_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln23_fu_913_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal B_squared_fu_919_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln29_fu_286_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal mul_ln30_fu_966_p0 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln30_fu_966_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal t1_fu_933_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln_fu_952_p4 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln32_fu_982_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln32_1_fu_986_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal trunc_ln1_fu_972_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln32_fu_990_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln32_2_fu_996_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln32_fu_290_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal Ex_2_fu_1006_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_1034_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_fu_1052_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal out_bits_fu_1044_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_1070_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_bits_2_fu_1062_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_1088_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_fu_1020_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln291_fu_1106_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_fu_1080_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln291_fu_1110_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_1_fu_1098_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_shift_1_fu_1116_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln291_1_fu_1132_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln292_fu_1120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln290_fu_1126_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln252_fu_1030_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln300_fu_1150_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln300_fu_1156_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shift_1_fu_1142_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal newexp_fu_1160_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_15_fu_1166_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln306_fu_1174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln291_1_fu_1136_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_1186_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_14_fu_1196_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln306_fu_1180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln282_fu_1232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln282_fu_1225_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_1214_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln259_fu_1218_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal results_exp_fu_1237_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln271_1_fu_1252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln271_fu_1256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln292_fu_1206_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln271_fu_1270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln271_3_fu_1262_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal select_ln271_fu_1274_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal results_exp_1_fu_1245_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal results_sig_fu_1282_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal t_2_fu_1290_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to4 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_reset_start_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal h_fu_294_p10 : STD_LOGIC_VECTOR (79 downto 0);
    signal mul_ln29_fu_286_p10 : STD_LOGIC_VECTOR (44 downto 0);
    signal mul_ln30_fu_966_p00 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln32_fu_290_p10 : STD_LOGIC_VECTOR (57 downto 0);
    signal tmp_1_fu_603_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_603_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_603_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_603_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_603_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_603_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_603_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_603_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_11_fu_713_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_713_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_785_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component hestonEuro_mul_23s_22ns_45_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (22 downto 0);
        din1 : IN STD_LOGIC_VECTOR (21 downto 0);
        dout : OUT STD_LOGIC_VECTOR (44 downto 0) );
    end component;


    component hestonEuro_mul_30s_29ns_58_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (29 downto 0);
        din1 : IN STD_LOGIC_VECTOR (28 downto 0);
        dout : OUT STD_LOGIC_VECTOR (57 downto 0) );
    end component;


    component hestonEuro_mul_80s_24ns_80_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (79 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (79 downto 0) );
    end component;


    component hestonEuro_sparsemux_17_3_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component hestonEuro_sparsemux_33_4_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        din8 : IN STD_LOGIC_VECTOR (0 downto 0);
        din9 : IN STD_LOGIC_VECTOR (0 downto 0);
        din10 : IN STD_LOGIC_VECTOR (0 downto 0);
        din11 : IN STD_LOGIC_VECTOR (0 downto 0);
        din12 : IN STD_LOGIC_VECTOR (0 downto 0);
        din13 : IN STD_LOGIC_VECTOR (0 downto 0);
        din14 : IN STD_LOGIC_VECTOR (0 downto 0);
        din15 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component hestonEuro_mul_15ns_15ns_30_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component hestonEuro_mul_15ns_15s_30_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component hestonEuro_sin_or_cos_float_s_ref_4oPi_table_100_ROM_1P_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (99 downto 0) );
    end component;


    component hestonEuro_sin_or_cos_float_s_second_order_float_sin_cos_K0_ROM_1P_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component hestonEuro_sin_or_cos_float_s_second_order_float_sin_cos_K1_ROM_1P_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (22 downto 0) );
    end component;


    component hestonEuro_sin_or_cos_float_s_second_order_float_sin_cos_K2_ROM_1P_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;



begin
    ref_4oPi_table_100_U : component hestonEuro_sin_or_cos_float_s_ref_4oPi_table_100_ROM_1P_LUTRAM_1R
    generic map (
        DataWidth => 100,
        AddressRange => 13,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ref_4oPi_table_100_address0,
        ce0 => ref_4oPi_table_100_ce0,
        q0 => ref_4oPi_table_100_q0);

    second_order_float_sin_cos_K0_U : component hestonEuro_sin_or_cos_float_s_second_order_float_sin_cos_K0_ROM_1P_LUTRAM_1R
    generic map (
        DataWidth => 30,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_order_float_sin_cos_K0_address0,
        ce0 => second_order_float_sin_cos_K0_ce0,
        q0 => second_order_float_sin_cos_K0_q0);

    second_order_float_sin_cos_K1_U : component hestonEuro_sin_or_cos_float_s_second_order_float_sin_cos_K1_ROM_1P_LUTRAM_1R
    generic map (
        DataWidth => 23,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_order_float_sin_cos_K1_address0,
        ce0 => second_order_float_sin_cos_K1_ce0,
        q0 => second_order_float_sin_cos_K1_q0);

    second_order_float_sin_cos_K2_U : component hestonEuro_sin_or_cos_float_s_second_order_float_sin_cos_K2_ROM_1P_LUTRAM_1R
    generic map (
        DataWidth => 15,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_order_float_sin_cos_K2_address0,
        ce0 => second_order_float_sin_cos_K2_ce0,
        q0 => second_order_float_sin_cos_K2_q0);

    mul_23s_22ns_45_1_1_U2 : component hestonEuro_mul_23s_22ns_45_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 23,
        din1_WIDTH => 22,
        dout_WIDTH => 45)
    port map (
        din0 => second_order_float_sin_cos_K1_q0,
        din1 => mul_ln29_fu_286_p1,
        dout => mul_ln29_fu_286_p2);

    mul_30s_29ns_58_1_1_U3 : component hestonEuro_mul_30s_29ns_58_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 30,
        din1_WIDTH => 29,
        dout_WIDTH => 58)
    port map (
        din0 => add_ln32_1_reg_1437,
        din1 => mul_ln32_fu_290_p1,
        dout => mul_ln32_fu_290_p2);

    mul_80s_24ns_80_1_1_U4 : component hestonEuro_mul_80s_24ns_80_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 80,
        din1_WIDTH => 24,
        dout_WIDTH => 80)
    port map (
        din0 => Med_reg_1347,
        din1 => h_fu_294_p1,
        dout => h_fu_294_p2);

    sparsemux_17_3_1_1_1_U5 : component hestonEuro_sparsemux_17_3_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 1,
        CASE1 => "001",
        din1_WIDTH => 1,
        CASE2 => "010",
        din2_WIDTH => 1,
        CASE3 => "011",
        din3_WIDTH => 1,
        CASE4 => "100",
        din4_WIDTH => 1,
        CASE5 => "101",
        din5_WIDTH => 1,
        CASE6 => "110",
        din6_WIDTH => 1,
        CASE7 => "111",
        din7_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 3,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_1,
        din2 => ap_const_lv1_1,
        din3 => ap_const_lv1_0,
        din4 => ap_const_lv1_0,
        din5 => ap_const_lv1_1,
        din6 => ap_const_lv1_1,
        din7 => ap_const_lv1_0,
        def => tmp_1_fu_603_p17,
        sel => k_1_fu_516_p3,
        dout => tmp_1_fu_603_p19);

    sparsemux_33_4_1_1_1_U6 : component hestonEuro_sparsemux_33_4_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 1,
        CASE1 => "0001",
        din1_WIDTH => 1,
        CASE2 => "0010",
        din2_WIDTH => 1,
        CASE3 => "0011",
        din3_WIDTH => 1,
        CASE4 => "0100",
        din4_WIDTH => 1,
        CASE5 => "0101",
        din5_WIDTH => 1,
        CASE6 => "0110",
        din6_WIDTH => 1,
        CASE7 => "0111",
        din7_WIDTH => 1,
        CASE8 => "1000",
        din8_WIDTH => 1,
        CASE9 => "1001",
        din9_WIDTH => 1,
        CASE10 => "1010",
        din10_WIDTH => 1,
        CASE11 => "1011",
        din11_WIDTH => 1,
        CASE12 => "1100",
        din12_WIDTH => 1,
        CASE13 => "1101",
        din13_WIDTH => 1,
        CASE14 => "1110",
        din14_WIDTH => 1,
        CASE15 => "1111",
        din15_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_0,
        din3 => ap_const_lv1_1,
        din4 => ap_const_lv1_1,
        din5 => ap_const_lv1_1,
        din6 => ap_const_lv1_1,
        din7 => ap_const_lv1_0,
        din8 => ap_const_lv1_0,
        din9 => ap_const_lv1_1,
        din10 => ap_const_lv1_1,
        din11 => ap_const_lv1_1,
        din12 => ap_const_lv1_1,
        din13 => ap_const_lv1_0,
        din14 => ap_const_lv1_0,
        din15 => ap_const_lv1_0,
        def => tmp_11_fu_713_p33,
        sel => index_fu_706_p3,
        dout => tmp_11_fu_713_p35);

    sparsemux_33_4_1_1_1_U7 : component hestonEuro_sparsemux_33_4_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 1,
        CASE1 => "0001",
        din1_WIDTH => 1,
        CASE2 => "0010",
        din2_WIDTH => 1,
        CASE3 => "0011",
        din3_WIDTH => 1,
        CASE4 => "0100",
        din4_WIDTH => 1,
        CASE5 => "0101",
        din5_WIDTH => 1,
        CASE6 => "0110",
        din6_WIDTH => 1,
        CASE7 => "0111",
        din7_WIDTH => 1,
        CASE8 => "1000",
        din8_WIDTH => 1,
        CASE9 => "1001",
        din9_WIDTH => 1,
        CASE10 => "1010",
        din10_WIDTH => 1,
        CASE11 => "1011",
        din11_WIDTH => 1,
        CASE12 => "1100",
        din12_WIDTH => 1,
        CASE13 => "1101",
        din13_WIDTH => 1,
        CASE14 => "1110",
        din14_WIDTH => 1,
        CASE15 => "1111",
        din15_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_1,
        din3 => ap_const_lv1_0,
        din4 => ap_const_lv1_1,
        din5 => ap_const_lv1_1,
        din6 => ap_const_lv1_0,
        din7 => ap_const_lv1_1,
        din8 => ap_const_lv1_1,
        din9 => ap_const_lv1_0,
        din10 => ap_const_lv1_1,
        din11 => ap_const_lv1_1,
        din12 => ap_const_lv1_0,
        din13 => ap_const_lv1_1,
        din14 => ap_const_lv1_0,
        din15 => ap_const_lv1_0,
        def => tmp_12_fu_785_p33,
        sel => index_fu_706_p3,
        dout => tmp_12_fu_785_p35);

    mul_15ns_15ns_30_1_1_U8 : component hestonEuro_mul_15ns_15ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln23_fu_913_p0,
        din1 => mul_ln23_fu_913_p1,
        dout => mul_ln23_fu_913_p2);

    mul_15ns_15s_30_1_1_U9 : component hestonEuro_mul_15ns_15s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln30_fu_966_p0,
        din1 => second_order_float_sin_cos_K2_q0,
        dout => mul_ln30_fu_966_p2);





    B_reg_1379_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                B_reg_1379 <= ap_const_lv22_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    B_reg_1379 <= B_fu_599_p1;
                end if; 
            end if;
        end if;
    end process;


    B_trunc_reg_1394_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                B_trunc_reg_1394 <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    B_trunc_reg_1394 <= select_ln506_1_fu_591_p3(21 downto 7);
                end if; 
            end if;
        end if;
    end process;


    Ex_1_reg_1374_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                Ex_1_reg_1374 <= ap_const_lv8_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    Ex_1_reg_1374 <= Ex_1_fu_543_p2;
                end if; 
            end if;
        end if;
    end process;


    Ex_1_reg_1374_pp0_iter4_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                Ex_1_reg_1374_pp0_iter4_reg <= ap_const_lv8_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    Ex_1_reg_1374_pp0_iter4_reg <= Ex_1_reg_1374;
                end if; 
            end if;
        end if;
    end process;


    Med_reg_1347_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                Med_reg_1347 <= ap_const_lv80_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    Med_reg_1347 <= shl_ln379_fu_366_p2(99 downto 20);
                end if; 
            end if;
        end if;
    end process;


    Mx_1_reg_1389_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                Mx_1_reg_1389 <= ap_const_lv29_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    Mx_1_reg_1389 <= Mx_1_fu_656_p3;
                end if; 
            end if;
        end if;
    end process;


    Mx_1_reg_1389_pp0_iter4_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                Mx_1_reg_1389_pp0_iter4_reg <= ap_const_lv29_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    Mx_1_reg_1389_pp0_iter4_reg <= Mx_1_reg_1389;
                end if; 
            end if;
        end if;
    end process;


    Mx_bits_3_reg_1357_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                Mx_bits_3_reg_1357 <= ap_const_lv58_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    Mx_bits_3_reg_1357 <= Mx_bits_3_fu_439_p3;
                end if; 
            end if;
        end if;
    end process;


    Mx_zeros_reg_1362_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                Mx_zeros_reg_1362 <= ap_const_lv6_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    Mx_zeros_reg_1362 <= Mx_zeros_fu_495_p1;
                end if; 
            end if;
        end if;
    end process;


    add_ln32_1_reg_1437_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                add_ln32_1_reg_1437 <= ap_const_lv30_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    add_ln32_1_reg_1437 <= add_ln32_1_fu_1000_p2;
                end if; 
            end if;
        end if;
    end process;


    and_ln271_reg_1419_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                and_ln271_reg_1419 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    and_ln271_reg_1419 <= and_ln271_fu_870_p2;
                end if; 
            end if;
        end if;
    end process;


    and_ln271_reg_1419_pp0_iter4_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                and_ln271_reg_1419_pp0_iter4_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    and_ln271_reg_1419_pp0_iter4_reg <= and_ln271_reg_1419;
                end if; 
            end if;
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    closepath_reg_1330_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                closepath_reg_1330 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    closepath_reg_1330 <= closepath_fu_324_p2;
                end if; 
            end if;
        end if;
    end process;


    closepath_reg_1330_pp0_iter1_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                closepath_reg_1330_pp0_iter1_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    closepath_reg_1330_pp0_iter1_reg <= closepath_reg_1330;
                end if; 
            end if;
        end if;
    end process;


    closepath_reg_1330_pp0_iter2_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                closepath_reg_1330_pp0_iter2_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    closepath_reg_1330_pp0_iter2_reg <= closepath_reg_1330_pp0_iter1_reg;
                end if; 
            end if;
        end if;
    end process;


    cos_basis_reg_1384_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                cos_basis_reg_1384 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    cos_basis_reg_1384 <= cos_basis_fu_649_p3;
                end if; 
            end if;
        end if;
    end process;


    cos_basis_reg_1384_pp0_iter4_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                cos_basis_reg_1384_pp0_iter4_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    cos_basis_reg_1384_pp0_iter4_reg <= cos_basis_reg_1384;
                end if; 
            end if;
        end if;
    end process;


    din_exp_reg_1317_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                din_exp_reg_1317 <= ap_const_lv8_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    din_exp_reg_1317 <= data_fu_298_p1(30 downto 23);
                end if; 
            end if;
        end if;
    end process;


    din_exp_reg_1317_pp0_iter1_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                din_exp_reg_1317_pp0_iter1_reg <= ap_const_lv8_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    din_exp_reg_1317_pp0_iter1_reg <= din_exp_reg_1317;
                end if; 
            end if;
        end if;
    end process;


    din_exp_reg_1317_pp0_iter2_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                din_exp_reg_1317_pp0_iter2_reg <= ap_const_lv8_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    din_exp_reg_1317_pp0_iter2_reg <= din_exp_reg_1317_pp0_iter1_reg;
                end if; 
            end if;
        end if;
    end process;


    din_sig_reg_1324_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                din_sig_reg_1324 <= ap_const_lv23_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    din_sig_reg_1324 <= din_sig_fu_320_p1;
                end if; 
            end if;
        end if;
    end process;


    din_sig_reg_1324_pp0_iter1_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                din_sig_reg_1324_pp0_iter1_reg <= ap_const_lv23_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    din_sig_reg_1324_pp0_iter1_reg <= din_sig_reg_1324;
                end if; 
            end if;
        end if;
    end process;


    din_sign_reg_1311_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                din_sign_reg_1311 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    din_sign_reg_1311 <= data_fu_298_p1(31 downto 31);
                end if; 
            end if;
        end if;
    end process;


    din_sign_reg_1311_pp0_iter1_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                din_sign_reg_1311_pp0_iter1_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    din_sign_reg_1311_pp0_iter1_reg <= din_sign_reg_1311;
                end if; 
            end if;
        end if;
    end process;


    din_sign_reg_1311_pp0_iter2_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                din_sign_reg_1311_pp0_iter2_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    din_sign_reg_1311_pp0_iter2_reg <= din_sign_reg_1311_pp0_iter1_reg;
                end if; 
            end if;
        end if;
    end process;


    do_cos_read_reg_1303_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                do_cos_read_reg_1303 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    do_cos_read_reg_1303 <= do_cos;
                end if; 
            end if;
        end if;
    end process;


    do_cos_read_reg_1303_pp0_iter1_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                do_cos_read_reg_1303_pp0_iter1_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    do_cos_read_reg_1303_pp0_iter1_reg <= do_cos_read_reg_1303;
                end if; 
            end if;
        end if;
    end process;


    do_cos_read_reg_1303_pp0_iter2_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                do_cos_read_reg_1303_pp0_iter2_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    do_cos_read_reg_1303_pp0_iter2_reg <= do_cos_read_reg_1303_pp0_iter1_reg;
                end if; 
            end if;
        end if;
    end process;


    do_cos_read_reg_1303_pp0_iter3_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                do_cos_read_reg_1303_pp0_iter3_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    do_cos_read_reg_1303_pp0_iter3_reg <= do_cos_read_reg_1303_pp0_iter2_reg;
                end if; 
            end if;
        end if;
    end process;


    do_cos_read_reg_1303_pp0_iter4_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                do_cos_read_reg_1303_pp0_iter4_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    do_cos_read_reg_1303_pp0_iter4_reg <= do_cos_read_reg_1303_pp0_iter3_reg;
                end if; 
            end if;
        end if;
    end process;


    icmp_ln271_1_reg_1368_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                icmp_ln271_1_reg_1368 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    icmp_ln271_1_reg_1368 <= icmp_ln271_1_fu_499_p2;
                end if; 
            end if;
        end if;
    end process;


    icmp_ln271_1_reg_1368_pp0_iter3_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                icmp_ln271_1_reg_1368_pp0_iter3_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    icmp_ln271_1_reg_1368_pp0_iter3_reg <= icmp_ln271_1_reg_1368;
                end if; 
            end if;
        end if;
    end process;


    icmp_ln271_1_reg_1368_pp0_iter4_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                icmp_ln271_1_reg_1368_pp0_iter4_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    icmp_ln271_1_reg_1368_pp0_iter4_reg <= icmp_ln271_1_reg_1368_pp0_iter3_reg;
                end if; 
            end if;
        end if;
    end process;


    icmp_ln271_reg_1414_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                icmp_ln271_reg_1414 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    icmp_ln271_reg_1414 <= icmp_ln271_fu_865_p2;
                end if; 
            end if;
        end if;
    end process;


    icmp_ln271_reg_1414_pp0_iter4_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                icmp_ln271_reg_1414_pp0_iter4_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    icmp_ln271_reg_1414_pp0_iter4_reg <= icmp_ln271_reg_1414;
                end if; 
            end if;
        end if;
    end process;


    icmp_ln282_reg_1425_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                icmp_ln282_reg_1425 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    icmp_ln282_reg_1425 <= icmp_ln282_fu_885_p2;
                end if; 
            end if;
        end if;
    end process;


    icmp_ln282_reg_1425_pp0_iter4_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                icmp_ln282_reg_1425_pp0_iter4_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    icmp_ln282_reg_1425_pp0_iter4_reg <= icmp_ln282_reg_1425;
                end if; 
            end if;
        end if;
    end process;


    k_reg_1352_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                k_reg_1352 <= ap_const_lv3_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    k_reg_1352 <= h_fu_294_p2(79 downto 77);
                end if; 
            end if;
        end if;
    end process;


    results_sign_4_reg_1432_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                results_sign_4_reg_1432 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    results_sign_4_reg_1432 <= results_sign_4_fu_902_p3;
                end if; 
            end if;
        end if;
    end process;


    results_sign_4_reg_1432_pp0_iter4_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                results_sign_4_reg_1432_pp0_iter4_reg <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                    results_sign_4_reg_1432_pp0_iter4_reg <= results_sign_4_reg_1432;
                end if; 
            end if;
        end if;
    end process;


    trunc_ln379_reg_1342_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                trunc_ln379_reg_1342 <= ap_const_lv4_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    trunc_ln379_reg_1342 <= trunc_ln379_fu_359_p1;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0, ap_reset_start_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    A_fu_691_p3 <= (sin_basis_fu_684_p3 & tmp_3_fu_664_p4);
    B_fu_599_p1 <= select_ln506_1_fu_591_p3(22 - 1 downto 0);
    B_squared_fu_919_p4 <= mul_ln23_fu_913_p2(29 downto 15);
    Ex_1_fu_543_p2 <= std_logic_vector(unsigned(select_ln453_fu_509_p3) - unsigned(zext_ln505_fu_522_p1));
    Ex_2_fu_1006_p3 <= 
        ap_const_lv8_0 when (cos_basis_reg_1384_pp0_iter4_reg(0) = '1') else 
        Ex_1_reg_1374_pp0_iter4_reg;
    Ex_fu_504_p2 <= std_logic_vector(unsigned(din_exp_reg_1317_pp0_iter2_reg) + unsigned(ap_const_lv8_83));
    Mx_1_fu_656_p3 <= 
        ap_const_lv29_1FFFFFFF when (cos_basis_fu_649_p3(0) = '1') else 
        Mx_fu_533_p4;
    Mx_bits_1_fu_433_p2 <= std_logic_vector(unsigned(ap_const_lv58_0) - unsigned(Mx_bits_fu_394_p4));
    Mx_bits_3_fu_439_p3 <= 
        Mx_bits_1_fu_433_p2 when (and_ln451_fu_427_p2(0) = '1') else 
        Mx_bits_fu_394_p4;
    Mx_bits_fu_394_p4 <= h_fu_294_p2(76 downto 19);
    Mx_fu_533_p4 <= shl_ln504_fu_528_p2(57 downto 29);
    Mx_zeros_fu_495_p1 <= tmp_s_fu_487_p3(6 - 1 downto 0);
    X_fu_382_p3 <= (ap_const_lv1_1 & din_sig_reg_1324_pp0_iter1_reg);
    add_ln290_fu_1126_p2 <= std_logic_vector(unsigned(c_1_fu_1098_p3) + unsigned(ap_const_lv32_10));
    add_ln300_fu_1150_p2 <= std_logic_vector(signed(sext_ln252_fu_1030_p1) + signed(ap_const_lv9_7F));
    add_ln32_1_fu_1000_p2 <= std_logic_vector(unsigned(add_ln32_fu_990_p2) + unsigned(sext_ln32_2_fu_996_p1));
    add_ln32_fu_990_p2 <= std_logic_vector(signed(sext_ln32_fu_982_p1) + signed(sext_ln32_1_fu_986_p1));
    add_ln376_fu_330_p2 <= std_logic_vector(unsigned(din_exp_fu_310_p4) + unsigned(ap_const_lv8_C2));
    addr_fu_336_p3 <= 
        ap_const_lv8_3F when (closepath_fu_324_p2(0) = '1') else 
        add_ln376_fu_330_p2;
    and_ln271_1_fu_1252_p2 <= (icmp_ln271_reg_1414_pp0_iter4_reg and icmp_ln271_1_reg_1368_pp0_iter4_reg);
    and_ln271_fu_870_p2 <= (icmp_ln271_fu_865_p2 and icmp_ln271_1_reg_1368);
    and_ln451_fu_427_p2 <= (xor_ln451_fu_422_p2 and tmp_fu_414_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to4_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to4 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to4)
    begin
        if (((ap_idle_pp0_0to4 = ap_const_logic_1) and (ap_start = ap_const_logic_0))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_start_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to4)
    begin
        if (((ap_idle_pp0_0to4 = ap_const_logic_1) and (ap_start = ap_const_logic_1))) then 
            ap_reset_start_pp0 <= ap_const_logic_1;
        else 
            ap_reset_start_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= t_2_fu_1290_p4;
    
    c_1_fu_1098_p3_proc : process(tmp_10_fu_1088_p4)
    begin
        c_1_fu_1098_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if tmp_10_fu_1088_p4(i) = '1' then
                c_1_fu_1098_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    
    c_fu_1080_p3_proc : process(tmp_5_fu_1070_p4)
    begin
        c_fu_1080_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if tmp_5_fu_1070_p4(i) = '1' then
                c_fu_1080_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    closepath_fu_324_p2 <= "1" when (unsigned(din_exp_fu_310_p4) < unsigned(ap_const_lv8_7E)) else "0";
    cos_basis_fu_649_p3 <= 
        xor_ln242_fu_643_p2 when (do_cos_read_reg_1303_pp0_iter2_reg(0) = '1') else 
        tmp_1_fu_603_p19;
    data_fu_298_p1 <= t_in;
    din_exp_fu_310_p4 <= data_fu_298_p1(30 downto 23);
    din_sig_fu_320_p1 <= data_fu_298_p1(23 - 1 downto 0);
    empty_fu_1214_p1 <= newexp_fu_1160_p2(8 - 1 downto 0);
    h_fu_294_p1 <= h_fu_294_p10(24 - 1 downto 0);
    h_fu_294_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(X_fu_382_p3),80));
    icmp_ln271_1_fu_499_p2 <= "1" when (din_sig_reg_1324_pp0_iter1_reg = ap_const_lv23_0) else "0";
    icmp_ln271_fu_865_p2 <= "1" when (din_exp_reg_1317_pp0_iter2_reg = ap_const_lv8_0) else "0";
    icmp_ln282_fu_885_p2 <= "1" when (din_exp_reg_1317_pp0_iter2_reg = ap_const_lv8_FF) else "0";
    icmp_ln292_fu_1120_p2 <= "1" when (c_fu_1080_p3 = ap_const_lv32_10) else "0";
    icmp_ln306_fu_1174_p2 <= "1" when (result_fu_1020_p4 = ap_const_lv29_0) else "0";
    in_shift_1_fu_1116_p1 <= shl_ln291_fu_1110_p2(28 - 1 downto 0);
    index_fu_706_p3 <= (din_sign_reg_1311_pp0_iter2_reg & k_1_fu_516_p3);
    k_1_fu_516_p3 <= 
        ap_const_lv3_0 when (closepath_reg_1330_pp0_iter2_reg(0) = '1') else 
        k_reg_1352;
    lshr_ln506_fu_579_p2 <= std_logic_vector(shift_right(unsigned(zext_ln506_fu_575_p1),to_integer(unsigned('0' & zext_ln506_1_fu_571_p1(31-1 downto 0)))));
    lshr_ln_fu_344_p4 <= addr_fu_336_p3(7 downto 4);
    mul_ln23_fu_913_p0 <= zext_ln23_fu_910_p1(15 - 1 downto 0);
    mul_ln23_fu_913_p1 <= zext_ln23_fu_910_p1(15 - 1 downto 0);
    mul_ln29_fu_286_p1 <= mul_ln29_fu_286_p10(22 - 1 downto 0);
    mul_ln29_fu_286_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_reg_1379),45));
    mul_ln30_fu_966_p0 <= mul_ln30_fu_966_p00(15 - 1 downto 0);
    mul_ln30_fu_966_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_squared_fu_919_p4),30));
    mul_ln32_fu_290_p1 <= mul_ln32_fu_290_p10(29 - 1 downto 0);
    mul_ln32_fu_290_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_1_reg_1389_pp0_iter4_reg),58));
    newexp_fu_1160_p2 <= std_logic_vector(signed(sext_ln300_fu_1156_p1) - signed(shift_1_fu_1142_p3));
    or_ln271_fu_1270_p2 <= (icmp_ln282_reg_1425_pp0_iter4_reg or and_ln271_reg_1419_pp0_iter4_reg);
    or_ln282_fu_1232_p2 <= (or_ln306_fu_1180_p2 or icmp_ln282_reg_1425_pp0_iter4_reg);
    or_ln306_fu_1180_p2 <= (tmp_15_fu_1166_p3 or icmp_ln306_fu_1174_p2);
    out_bits_2_fu_1062_p3 <= (tmp_7_fu_1052_p4 & ap_const_lv19_40000);
    out_bits_fu_1044_p3 <= (tmp_4_fu_1034_p4 & ap_const_lv16_8000);
    ref_4oPi_table_100_address0 <= zext_ln378_fu_354_p1(4 - 1 downto 0);

    ref_4oPi_table_100_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ref_4oPi_table_100_ce0 <= ap_const_logic_1;
        else 
            ref_4oPi_table_100_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    result_fu_1020_p4 <= mul_ln32_fu_290_p2(57 downto 29);
    results_exp_1_fu_1245_p3 <= 
        select_ln259_fu_1218_p3 when (and_ln271_reg_1419_pp0_iter4_reg(0) = '1') else 
        results_exp_fu_1237_p3;
    results_exp_fu_1237_p3 <= 
        select_ln282_fu_1225_p3 when (or_ln282_fu_1232_p2(0) = '1') else 
        empty_fu_1214_p1;
    results_sig_fu_1282_p3 <= 
        select_ln271_3_fu_1262_p3 when (or_ln271_fu_1270_p2(0) = '1') else 
        select_ln271_fu_1274_p3;
    results_sign_2_fu_880_p2 <= (xor_ln278_fu_875_p2 and din_sign_reg_1311_pp0_iter2_reg);
    results_sign_3_fu_896_p2 <= (xor_ln282_fu_890_p2 and results_sign_fu_857_p3);
    results_sign_4_fu_902_p3 <= 
        results_sign_2_fu_880_p2 when (and_ln271_fu_870_p2(0) = '1') else 
        results_sign_3_fu_896_p2;
    results_sign_fu_857_p3 <= 
        tmp_11_fu_713_p35 when (cos_basis_fu_649_p3(0) = '1') else 
        tmp_12_fu_785_p35;
    second_order_float_sin_cos_K0_address0 <= zext_ln28_fu_699_p1(8 - 1 downto 0);

    second_order_float_sin_cos_K0_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce))) then 
            second_order_float_sin_cos_K0_ce0 <= ap_const_logic_1;
        else 
            second_order_float_sin_cos_K0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    second_order_float_sin_cos_K1_address0 <= zext_ln28_fu_699_p1(8 - 1 downto 0);

    second_order_float_sin_cos_K1_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce))) then 
            second_order_float_sin_cos_K1_ce0 <= ap_const_logic_1;
        else 
            second_order_float_sin_cos_K1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    second_order_float_sin_cos_K2_address0 <= zext_ln28_fu_699_p1(8 - 1 downto 0);

    second_order_float_sin_cos_K2_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce))) then 
            second_order_float_sin_cos_K2_ce0 <= ap_const_logic_1;
        else 
            second_order_float_sin_cos_K2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln259_fu_1218_p3 <= 
        ap_const_lv8_7F when (do_cos_read_reg_1303_pp0_iter4_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln271_3_fu_1262_p3 <= 
        ap_const_lv23_7FFFFF when (xor_ln271_fu_1256_p2(0) = '1') else 
        ap_const_lv23_0;
    select_ln271_fu_1274_p3 <= 
        ap_const_lv23_0 when (or_ln306_fu_1180_p2(0) = '1') else 
        select_ln292_fu_1206_p3;
    select_ln282_fu_1225_p3 <= 
        ap_const_lv8_FF when (icmp_ln282_reg_1425_pp0_iter4_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln292_fu_1206_p3 <= 
        tmp_13_fu_1186_p4 when (icmp_ln292_fu_1120_p2(0) = '1') else 
        tmp_14_fu_1196_p4;
    select_ln453_fu_509_p3 <= 
        Ex_fu_504_p2 when (closepath_reg_1330_pp0_iter2_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln506_1_fu_591_p3 <= 
        lshr_ln506_fu_579_p2 when (tmp_6_fu_549_p3(0) = '1') else 
        shl_ln506_fu_585_p2;
    select_ln506_fu_563_p3 <= 
        sub_ln506_fu_557_p2 when (tmp_6_fu_549_p3(0) = '1') else 
        Ex_1_fu_543_p2;
        sext_ln252_fu_1030_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Ex_2_fu_1006_p3),9));

        sext_ln300_fu_1156_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln300_fu_1150_p2),32));

        sext_ln32_1_fu_986_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_952_p4),30));

        sext_ln32_2_fu_996_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_fu_972_p4),30));

        sext_ln32_fu_982_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(t1_fu_933_p4),30));

        sext_ln75_fu_483_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_9_fu_475_p3),32));

    shift_1_fu_1142_p3 <= 
        add_ln290_fu_1126_p2 when (icmp_ln292_fu_1120_p2(0) = '1') else 
        c_fu_1080_p3;
    shl_ln291_1_fu_1136_p2 <= std_logic_vector(shift_left(unsigned(zext_ln291_1_fu_1132_p1),to_integer(unsigned('0' & c_1_fu_1098_p3(31-1 downto 0)))));
    shl_ln291_fu_1110_p2 <= std_logic_vector(shift_left(unsigned(zext_ln291_fu_1106_p1),to_integer(unsigned('0' & c_fu_1080_p3(31-1 downto 0)))));
    shl_ln379_fu_366_p2 <= std_logic_vector(shift_left(unsigned(ref_4oPi_table_100_q0),to_integer(unsigned('0' & zext_ln379_fu_363_p1(31-1 downto 0)))));
    shl_ln504_fu_528_p2 <= std_logic_vector(shift_left(unsigned(Mx_bits_3_reg_1357),to_integer(unsigned('0' & zext_ln504_fu_525_p1(31-1 downto 0)))));
    shl_ln506_fu_585_p2 <= std_logic_vector(shift_left(unsigned(zext_ln506_fu_575_p1),to_integer(unsigned('0' & zext_ln506_1_fu_571_p1(31-1 downto 0)))));
    sin_basis_fu_684_p3 <= 
        tmp_1_fu_603_p19 when (do_cos_read_reg_1303_pp0_iter2_reg(0) = '1') else 
        xor_ln242_fu_643_p2;
    sub_ln506_fu_557_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(Ex_1_fu_543_p2));
    t1_fu_933_p4 <= second_order_float_sin_cos_K0_q0(29 downto 1);
    t_2_fu_1290_p4 <= ((results_sign_4_reg_1432_pp0_iter4_reg & results_exp_1_fu_1245_p3) & results_sig_fu_1282_p3);
    t_fu_457_p3 <= (tmp_2_fu_447_p4 & ap_const_lv1_1);
    
    tmp_10_fu_1088_p4_proc : process(out_bits_2_fu_1062_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_10_fu_1088_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_1F(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := out_bits_2_fu_1062_p3;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_1F(5-1 downto 0)));
            for tmp_10_fu_1088_p4_i in 0 to 32-1 loop
                v0_cpy(tmp_10_fu_1088_p4_i) := out_bits_2_fu_1062_p3(32-1-tmp_10_fu_1088_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_10_fu_1088_p4 <= resvalue(32-1 downto 0);
    end process;

    tmp_11_fu_713_p33 <= "X";
    tmp_12_fu_785_p33 <= "X";
    tmp_13_fu_1186_p4 <= shl_ln291_1_fu_1136_p2(27 downto 5);
    tmp_14_fu_1196_p4 <= shl_ln291_fu_1110_p2(27 downto 5);
    tmp_15_fu_1166_p3 <= newexp_fu_1160_p2(31 downto 31);
    tmp_1_fu_603_p17 <= "X";
    tmp_2_fu_447_p4 <= Mx_bits_3_fu_439_p3(57 downto 29);
    tmp_3_fu_664_p4 <= select_ln506_1_fu_591_p3(28 downto 22);
    tmp_4_fu_1034_p4 <= mul_ln32_fu_290_p2(57 downto 42);
    
    tmp_5_fu_1070_p4_proc : process(out_bits_fu_1044_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_5_fu_1070_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_1F(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := out_bits_fu_1044_p3;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_1F(5-1 downto 0)));
            for tmp_5_fu_1070_p4_i in 0 to 32-1 loop
                v0_cpy(tmp_5_fu_1070_p4_i) := out_bits_fu_1044_p3(32-1-tmp_5_fu_1070_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_5_fu_1070_p4 <= resvalue(32-1 downto 0);
    end process;

    tmp_6_fu_549_p3 <= Ex_1_fu_543_p2(7 downto 7);
    tmp_7_fu_1052_p4 <= mul_ln32_fu_290_p2(41 downto 29);
    
    tmp_8_fu_465_p4_proc : process(t_fu_457_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(30+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(30+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(30 - 1 downto 0);
    variable tmp_8_fu_465_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(30 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(30 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(30 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_1D(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := t_fu_457_p3;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(30-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(30-1-unsigned(ap_const_lv32_1D(5-1 downto 0)));
            for tmp_8_fu_465_p4_i in 0 to 30-1 loop
                v0_cpy(tmp_8_fu_465_p4_i) := t_fu_457_p3(30-1-tmp_8_fu_465_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(30-1 downto 0)))));
        res_mask := res_mask(30-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_8_fu_465_p4 <= resvalue(30-1 downto 0);
    end process;

    tmp_9_fu_475_p3 <= (ap_const_lv1_1 & tmp_8_fu_465_p4);
    tmp_fu_414_p3 <= h_fu_294_p2(77 downto 77);
    
    tmp_s_fu_487_p3_proc : process(sext_ln75_fu_483_p1)
    begin
        tmp_s_fu_487_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if sext_ln75_fu_483_p1(i) = '1' then
                tmp_s_fu_487_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    trunc_ln1_fu_972_p4 <= mul_ln30_fu_966_p2(29 downto 16);
    trunc_ln379_fu_359_p1 <= addr_fu_336_p3(4 - 1 downto 0);
    trunc_ln_fu_952_p4 <= mul_ln29_fu_286_p2(44 downto 23);
    xor_ln242_fu_643_p2 <= (tmp_1_fu_603_p19 xor ap_const_lv1_1);
    xor_ln271_fu_1256_p2 <= (ap_const_lv1_1 xor and_ln271_1_fu_1252_p2);
    xor_ln278_fu_875_p2 <= (do_cos_read_reg_1303_pp0_iter2_reg xor ap_const_lv1_1);
    xor_ln282_fu_890_p2 <= (icmp_ln282_fu_885_p2 xor ap_const_lv1_1);
    xor_ln451_fu_422_p2 <= (closepath_reg_1330_pp0_iter1_reg xor ap_const_lv1_1);
    zext_ln23_fu_910_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_trunc_reg_1394),30));
    zext_ln28_fu_699_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A_fu_691_p3),64));
    zext_ln291_1_fu_1132_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_shift_1_fu_1116_p1),32));
    zext_ln291_fu_1106_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_fu_1020_p4),32));
    zext_ln378_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_344_p4),64));
    zext_ln379_fu_363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln379_reg_1342),100));
    zext_ln504_fu_525_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_zeros_reg_1362),58));
    zext_ln505_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_zeros_reg_1362),8));
    zext_ln506_1_fu_571_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln506_fu_563_p3),32));
    zext_ln506_fu_575_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_fu_533_p4),32));
end behav;
