# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_hestonEuro_0_0/system_hestonEuro_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_hestonEuro_0_0 || ORIG_REF_NAME==system_hestonEuro_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps8_0_99M_0/system_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps8_0_99M_0 || ORIG_REF_NAME==system_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/system/ip/system_zynq_ultra_ps_e_0_0/system_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==system_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/system/ip/system_smartconnect_0_0/system_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_smartconnect_0_0 || ORIG_REF_NAME==system_smartconnect_0_0} -quiet] -quiet

# XDC: /home/jbonfigs/EECE5698_FinalProject/hw/hw.gen/sources_1/bd/system/system_ooc.xdc
